-- ============================================================
-- MISSING KEYS MIGRATION SQL
-- ============================================================
-- Total keys: 229 (191 FlutterFlow + 38 Phase 7)
-- Generated: 2026-02-22
-- ============================================================

-- ============================================================
-- FlutterFlow Page Keys (191 keys - 8-char IDs)
-- These were hardcoded in FlutterFlow pages, never in Supabase
-- ============================================================

INSERT INTO ui_translations (translation_key, language_code, translation_text, category)
VALUES
  ('01uw12sq', 'en', 'How we use your information', 'ui'),
  ('05aeogb1', 'en', 'Copenhagen', 'ui'),
  ('05aeogb1', 'da', 'København', 'ui'),
  ('05aeogb1', 'de', 'Kopenhagen', 'ui'),
  ('05aeogb1', 'fr', 'Copenhague', 'ui'),
  ('05aeogb1', 'it', 'Copenaghen', 'ui'),
  ('05aeogb1', 'no', 'København', 'ui'),
  ('05aeogb1', 'sv', 'Köpenhamn', 'ui'),
  ('0aq8qo7g', 'en', 'Localization', 'ui'),
  ('0aq8qo7g', 'da', 'Lokalisering', 'ui'),
  ('0aq8qo7g', 'de', 'Lokalisierung', 'ui'),
  ('0aq8qo7g', 'fr', 'Localisation', 'ui'),
  ('0aq8qo7g', 'it', 'Localizzazione', 'ui'),
  ('0aq8qo7g', 'no', 'Lokalisering', 'ui'),
  ('0aq8qo7g', 'sv', 'Lokalisering', 'ui'),
  ('0eehrkgn', 'en', 'Discover restaurants, cafés, and bars filtered by your lifestyle, preferences, and dietary needs.', 'ui'),
  ('0eehrkgn', 'da', 'Opdag restauranter, caféer og barer filtreret efter din livsstil, præferencer og kostbehov.', 'ui'),
  ('0eehrkgn', 'de', 'Entdecken Sie Restaurants, Cafés und Bars, gefiltert nach Ihrem Lebensstil, Ihren Vorlieben und Ernährungsbedürfnissen.', 'ui'),
  ('0eehrkgn', 'fr', 'Découvrez des restaurants, des cafés et des bars filtrés en fonction de votre style de vie, de vos préférences et de vos besoins alimentaires.', 'ui'),
  ('0eehrkgn', 'it', 'Scopri ristoranti, caffè e bar filtrati in base al tuo stile di vita, alle tue preferenze e alle tue esigenze alimentari.', 'ui'),
  ('0eehrkgn', 'no', 'Oppdag restauranter, kafeer og barer filtrert etter din livsstil, preferanser og kostholdsbehov.', 'ui'),
  ('0eehrkgn', 'sv', 'Upptäck restauranger, kaféer och barer filtrerade efter din livsstil, dina preferenser och dina kostbehov.', 'ui'),
  ('0j8lvplu', 'en', 'Changes to this policy', 'ui'),
  ('0qr5v44h', 'en', 'Introduction', 'ui'),
  ('103bep6k', 'en', 'Closed', 'ui'),
  ('103bep6k', 'da', 'Lukket', 'ui'),
  ('103bep6k', 'de', 'Zu', 'ui'),
  ('103bep6k', 'fr', 'Fermé', 'ui'),
  ('103bep6k', 'it', 'Chiuso', 'ui'),
  ('103bep6k', 'no', 'Lukket', 'ui'),
  ('103bep6k', 'sv', 'Stängd', 'ui'),
  ('1fqmkf0t', 'en', '• Comply with legal obligations', 'ui'),
  ('1pizlbas', 'en', 'Data storage and security', 'ui'),
  ('1smig27j', 'en', 'Hide filters', 'ui'),
  ('1smig27j', 'da', 'Skjul filtre', 'ui'),
  ('1smig27j', 'de', 'Filter ausblenden', 'ui'),
  ('1smig27j', 'fr', 'Masquer les filtres', 'ui'),
  ('1smig27j', 'it', 'Nascondi filtri', 'ui'),
  ('1smig27j', 'no', 'Skjul filtre', 'ui'),
  ('1smig27j', 'sv', 'Dölj filter', 'ui'),
  ('24nk41wt', 'en', 'Hello World', 'ui'),
  ('290fbi5g', 'en', 'Localization', 'ui'),
  ('290fbi5g', 'da', 'Indstillinger', 'ui'),
  ('290fbi5g', 'de', 'Einstellungen', 'ui'),
  ('290fbi5g', 'fr', 'Paramètres', 'ui'),
  ('290fbi5g', 'it', 'Impostazioni', 'ui'),
  ('290fbi5g', 'no', 'Innstillinger', 'ui'),
  ('290fbi5g', 'sv', 'Inställningar', 'ui'),
  ('297ogtn9', 'en', 'Are we missing a place?', 'ui'),
  ('297ogtn9', 'da', 'Mangler vi et sted?', 'ui'),
  ('297ogtn9', 'de', 'Fehlt uns ein Ort?', 'ui'),
  ('297ogtn9', 'fr', 'Il nous manque un endroit ?', 'ui'),
  ('297ogtn9', 'it', 'Ci manca un posto?', 'ui'),
  ('297ogtn9', 'no', 'Mangler vi et sted?', 'ui'),
  ('297ogtn9', 'sv', 'Saknar vi en plats?', 'ui'),
  ('2hj5mmov', 'en', 'Go to Settings', 'ui'),
  ('2hj5mmov', 'da', 'Åben indstillinger', 'ui'),
  ('2hj5mmov', 'de', 'Zu den Einstellungen', 'ui'),
  ('2hj5mmov', 'fr', 'Aller aux paramètres', 'ui'),
  ('2hj5mmov', 'it', 'Vai alle impostazioni', 'ui'),
  ('2hj5mmov', 'no', 'Gå til innstillinger', 'ui'),
  ('2hj5mmov', 'sv', 'Gå till inställningar', 'ui'),
  ('2snqj7a7', 'en', 'Home', 'ui'),
  ('2snqj7a7', 'da', 'Hjem', 'ui'),
  ('2snqj7a7', 'de', 'Startseite', 'ui'),
  ('2snqj7a7', 'fr', 'Accueil', 'ui'),
  ('2snqj7a7', 'it', 'Home', 'ui'),
  ('2snqj7a7', 'no', 'Hjem', 'ui'),
  ('2snqj7a7', 'sv', 'Hem', 'ui'),
  ('2v106a6z', 'en', 'Terms of use', 'ui'),
  ('2v106a6z', 'da', 'Brugsbetingelser', 'ui'),
  ('2v106a6z', 'de', 'Nutzungsbedingungen', 'ui'),
  ('2v106a6z', 'fr', 'Conditions d''utilisation', 'ui'),
  ('2v106a6z', 'it', 'Termini di utilizzo', 'ui'),
  ('2v106a6z', 'no', 'Bruksvilkår', 'ui'),
  ('2v106a6z', 'sv', 'Användarvillkor', 'ui'),
  ('35r2ixsz', 'en', 'Instagram', 'ui'),
  ('35r2ixsz', 'da', 'Instagram', 'ui'),
  ('35r2ixsz', 'de', 'Instagram', 'ui'),
  ('35r2ixsz', 'fr', 'Instagram', 'ui'),
  ('35r2ixsz', 'it', 'Instagram', 'ui'),
  ('35r2ixsz', 'no', 'Instagram', 'ui'),
  ('35r2ixsz', 'sv', 'Instagram', 'ui'),
  ('3c484afo', 'en', '• Opt out of location services', 'ui'),
  ('3dn3iu2l', 'en', 'Settings', 'ui'),
  ('3dn3iu2l', 'da', 'Indstillinger', 'ui'),
  ('3dn3iu2l', 'de', 'Einstellungen', 'ui'),
  ('3dn3iu2l', 'fr', 'Paramètres', 'ui'),
  ('3dn3iu2l', 'it', 'Impostazioni', 'ui'),
  ('3dn3iu2l', 'no', 'Innstillinger', 'ui'),
  ('3dn3iu2l', 'sv', 'Inställningar', 'ui'),
  ('3i7o36gd', 'en', 'About', 'ui'),
  ('3i7o36gd', 'da', 'Om', 'ui'),
  ('3i7o36gd', 'de', 'Info', 'ui'),
  ('3i7o36gd', 'fr', 'À propos', 'ui'),
  ('3i7o36gd', 'it', 'Info', 'ui'),
  ('3i7o36gd', 'no', 'Om', 'ui'),
  ('3i7o36gd', 'sv', 'Om', 'ui'),
  ('3r57tlpr', 'en', 'Turn on location sharing', 'ui'),
  ('3r57tlpr', 'da', 'Slå lokationsdeling til', 'ui'),
  ('3r57tlpr', 'de', 'Aktivieren Sie die Standortfreigabe', 'ui'),
  ('3r57tlpr', 'fr', 'Activer le partage de position', 'ui'),
  ('3r57tlpr', 'it', 'Attiva la condivisione della posizione', 'ui'),
  ('3r57tlpr', 'no', 'Slå på posisjonsdeling', 'ui'),
  ('3r57tlpr', 'sv', 'Aktivera platsdelning', 'ui'),
  ('3sgje096', 'en', 'Account', 'ui'),
  ('3sgje096', 'da', 'Konto', 'ui'),
  ('3sgje096', 'de', 'Konto', 'ui'),
  ('3sgje096', 'fr', 'Compte', 'ui'),
  ('3sgje096', 'it', 'Account', 'ui'),
  ('3sgje096', 'no', 'Konto', 'ui'),
  ('3sgje096', 'sv', 'Konto', 'ui'),
  ('3tlbn2an', 'en', 'My JourneyMate', 'ui'),
  ('3tlbn2an', 'da', 'Mit JourneyMate', 'ui'),
  ('3tlbn2an', 'de', 'Mein JourneyMate', 'ui'),
  ('3tlbn2an', 'fr', 'Mon JourneyMate', 'ui'),
  ('3tlbn2an', 'it', 'Il mio JourneyMate', 'ui'),
  ('3tlbn2an', 'no', 'Min JourneyMate', 'ui'),
  ('3tlbn2an', 'sv', 'Min JourneyMate', 'ui'),
  ('4dnrmcoa', 'en', '•', 'ui'),
  ('4dnrmcoa', 'da', '•', 'ui'),
  ('4dnrmcoa', 'de', '•', 'ui'),
  ('4dnrmcoa', 'fr', '•', 'ui'),
  ('4dnrmcoa', 'it', '•', 'ui'),
  ('4dnrmcoa', 'no', '•', 'ui'),
  ('4dnrmcoa', 'sv', '•', 'ui'),
  ('4p3u9ngw', 'en', 'Send email', 'ui'),
  ('4p3u9ngw', 'da', 'Send e-mail', 'ui'),
  ('4p3u9ngw', 'de', 'E-Mail senden', 'ui'),
  ('4p3u9ngw', 'fr', 'Envoyer un e-mail', 'ui'),
  ('4p3u9ngw', 'it', 'Invia email', 'ui'),
  ('4p3u9ngw', 'no', 'Send e-post', 'ui'),
  ('4p3u9ngw', 'sv', 'Skicka e-post', 'ui'),
  ('51lrsce5', 'en', '• Respond to government requests', 'ui'),
  ('5hz5m6k5', 'en', 'European Union Residents', 'ui'),
  ('5rrmp4f2', 'en', 'Search', 'ui'),
  ('5rrmp4f2', 'da', 'Søg', 'ui'),
  ('5rrmp4f2', 'de', 'Suche', 'ui'),
  ('5rrmp4f2', 'fr', 'Recherche', 'ui'),
  ('5rrmp4f2', 'it', 'Cerca', 'ui'),
  ('5rrmp4f2', 'no', 'Søk', 'ui'),
  ('5rrmp4f2', 'sv', 'Sök', 'ui'),
  ('6a5m8w10', 'en', 'This Privacy Policy describes how we collect, use, and handle your information when you use our application. We are committed to collecting only the minimum data necessary for the app to function properly while protecting your privacy.', 'ui'),
  ('6c2othh1', 'en', '• Access your data', 'ui'),
  ('6dww9uct', 'en', 'Welcome to\nJourneyMate', 'ui'),
  ('6dww9uct', 'da', 'Velkommen til\nJourneyMate', 'ui'),
  ('6dww9uct', 'de', 'Willkommen bei\nJourneyMate', 'ui'),
  ('6dww9uct', 'fr', 'Bienvenue chez\nJourneyMate', 'ui'),
  ('6dww9uct', 'it', 'Benvenuti a\nJourneyMate', 'ui'),
  ('6dww9uct', 'no', 'Velkommen til\nJourneyMate', 'ui'),
  ('6dww9uct', 'sv', 'Välkommen till\nJourneyMate', 'ui'),
  ('6f2losum', 'en', '•', 'ui'),
  ('6f2losum', 'da', '•', 'ui'),
  ('6f2losum', 'de', '•', 'ui'),
  ('6f2losum', 'fr', '•', 'ui'),
  ('6f2losum', 'it', '•', 'ui'),
  ('6f2losum', 'no', '•', 'ui'),
  ('6f2losum', 'sv', '•', 'ui'),
  ('6kxja9sp', 'en', 'Exchange rates are updated once every 24 hrs, so actual prices may vary slightly.', 'ui'),
  ('6kxja9sp', 'da', 'Valutakurser opdateres hver 24. time, så de faktiske priser kan afvige en smule.', 'ui'),
  ('6kxja9sp', 'de', 'Die Wechselkurse werden alle 24 Stunden aktualisiert, daher können die tatsächlichen Preise leicht abweichen.', 'ui'),
  ('6kxja9sp', 'fr', 'Les taux de change sont mis à jour toutes les 24 heures, les prix réels peuvent donc varier légèrement.', 'ui'),
  ('6kxja9sp', 'it', 'I tassi di cambio sono aggiornati ogni 24 ore, per cui i prezzi effettivi potrebbero variare leggermente.', 'ui'),
  ('6kxja9sp', 'no', 'Valutakursene oppdateres hver 24. time, så faktiske priser kan variere noe.', 'ui'),
  ('6kxja9sp', 'sv', 'Valutakurserna uppdateras var 24:e timme, så faktiska priser kan variera något.', 'ui'),
  ('6nflsf8i', 'en', '• We retain data only for as long as necessary to provide our services', 'ui'),
  ('6qnye4kv', 'en', 'Automatically Collected Information', 'ui'),
  ('6wrui6kv', 'en', 'Home', 'ui'),
  ('6wrui6kv', 'da', 'Hjem', 'ui'),
  ('6wrui6kv', 'de', 'Startseite', 'ui'),
  ('6wrui6kv', 'fr', 'Accueli', 'ui'),
  ('6wrui6kv', 'it', 'Home', 'ui'),
  ('6wrui6kv', 'no', 'Hjem', 'ui'),
  ('6wrui6kv', 'sv', 'Hem', 'ui'),
  ('6z95cbkb', 'en', 'Last brought up to date on ', 'ui'),
  ('6z95cbkb', 'da', 'Sidst ajourført den ', 'ui'),
  ('6z95cbkb', 'de', 'Zuletzt aktualisiert am ', 'ui'),
  ('6z95cbkb', 'fr', 'Dernière mise à jour ', 'ui'),
  ('6z95cbkb', 'it', 'Ultimo aggiornamento ', 'ui'),
  ('6z95cbkb', 'no', 'Sist ajourført ', 'ui'),
  ('6z95cbkb', 'sv', 'Senast ajourförd ', 'ui'),
  ('7bvip4jz', 'en', 'California Residents', 'ui'),
  ('7pk0thnp', 'en', 'Features, services & amenities', 'ui'),
  ('7pk0thnp', 'da', 'Faciliteter og services', 'ui'),
  ('7pk0thnp', 'de', 'Ausstattung & Services', 'ui'),
  ('7pk0thnp', 'fr', ' Services et équipements', 'ui'),
  ('7pk0thnp', 'it', 'Servizi e comfort', 'ui'),
  ('7pk0thnp', 'no', 'Fasiliteter og tjenester', 'ui'),
  ('7pk0thnp', 'sv', 'Faciliteter och service', 'ui'),
  ('82y059ik', 'en', 'Exchange rates are updated once every 24 hrs, so actual prices may vary slightly.', 'ui'),
  ('82y059ik', 'da', 'Valutakurser opdateres hver 24. time, så de faktiske priser kan afvige en smule.', 'ui'),
  ('82y059ik', 'de', 'Die Wechselkurse werden alle 24 Stunden aktualisiert, daher können die tatsächlichen Preise leicht abweichen.', 'ui'),
  ('82y059ik', 'fr', 'Les taux de change sont mis à jour toutes les 24 heures, les prix réels peuvent donc varier légèrement.', 'ui'),
  ('82y059ik', 'it', 'I tassi di cambio sono aggiornati ogni 24 ore, per cui i prezzi effettivi potrebbero variare leggermente.', 'ui'),
  ('82y059ik', 'no', 'Valutakursene oppdateres hver 24. time, så faktiske priser kan variere noe.', 'ui'),
  ('82y059ik', 'sv', 'Valutakurserna uppdateras var 24:e timme, så faktiska priser kan variera något.', 'ui'),
  ('85kcraoz', 'en', 'Information sharing', 'ui'),
  ('86ehku8w', 'en', 'Home', 'ui'),
  ('86ehku8w', 'da', 'Hjem', 'ui'),
  ('86ehku8w', 'de', 'Startseite', 'ui'),
  ('86ehku8w', 'fr', 'Accueil', 'ui'),
  ('86ehku8w', 'it', 'Home', 'ui'),
  ('86ehku8w', 'no', 'Hjem', 'ui'),
  ('86ehku8w', 'sv', 'Hem', 'ui'),
  ('8d0ioapy', 'en', 'Information we collect', 'ui'),
  ('8pvvg34m', 'en', 'Website', 'ui'),
  ('8pvvg34m', 'da', 'Hjemmeside', 'ui'),
  ('8pvvg34m', 'de', 'Webseite', 'ui'),
  ('8pvvg34m', 'fr', 'Site web', 'ui'),
  ('8pvvg34m', 'it', 'Sito web', 'ui'),
  ('8pvvg34m', 'no', 'Nettsted', 'ui'),
  ('8pvvg34m', 'sv', 'Webbplats', 'ui'),
  ('8tdbnfft', 'en', '• We do not store your location data history', 'ui'),
  ('96y9mb2l', 'en', '•', 'ui'),
  ('96y9mb2l', 'da', '•', 'ui'),
  ('96y9mb2l', 'de', '•', 'ui'),
  ('96y9mb2l', 'fr', '•', 'ui'),
  ('96y9mb2l', 'it', '•', 'ui'),
  ('96y9mb2l', 'no', '•', 'ui'),
  ('96y9mb2l', 'sv', '•', 'ui'),
  ('9hmbepnd', 'en', 'Visit website', 'ui'),
  ('9hmbepnd', 'da', 'Besøg hjemmeside', 'ui'),
  ('9hmbepnd', 'de', 'Website aufrufen', 'ui'),
  ('9hmbepnd', 'fr', 'Visitez le site Web', 'ui'),
  ('9hmbepnd', 'it', 'Visita il sito web', 'ui'),
  ('9hmbepnd', 'no', 'Besøk nettstedet', 'ui'),
  ('9hmbepnd', 'sv', 'Besök webbplatsen', 'ui'),
  ('9nldb2d7', 'en', 'Complete setup', 'ui'),
  ('9nldb2d7', 'da', 'Gå til appen', 'ui'),
  ('9nldb2d7', 'de', 'Einrichtung abschließen', 'ui'),
  ('9nldb2d7', 'fr', 'Accéder à l''application', 'ui'),
  ('9nldb2d7', 'it', 'Completa la configurazione', 'ui'),
  ('9nldb2d7', 'no', 'Fullfør oppsettet', 'ui'),
  ('9nldb2d7', 'sv', 'Gå till appen', 'ui'),
  ('9ojhl6tv', 'en', '• Device information (operating system version, device model)', 'ui'),
  ('9wk6mbas', 'en', 'Gallery', 'ui'),
  ('9wk6mbas', 'da', 'Galleri', 'ui'),
  ('9wk6mbas', 'de', 'Galerie', 'ui'),
  ('9wk6mbas', 'fr', 'Galerie', 'ui'),
  ('9wk6mbas', 'it', 'Galleria', 'ui'),
  ('9wk6mbas', 'no', 'Galleri', 'ui'),
  ('9wk6mbas', 'sv', 'Galleri', 'ui'),
  ('a7s58202', 'en', ':/', 'ui'),
  ('a7s58202', 'da', ':/', 'ui'),
  ('a7s58202', 'de', ':/', 'ui'),
  ('a7s58202', 'fr', ':/', 'ui'),
  ('a7s58202', 'it', ':/', 'ui'),
  ('a7s58202', 'no', ':/', 'ui'),
  ('a7s58202', 'sv', ':/', 'ui'),
  ('ax2mbofv', 'en', 'Children''s Privacy', 'ui'),
  ('b987t5cc', 'en', 'Gallery', 'ui'),
  ('b987t5cc', 'da', 'Galleri', 'ui'),
  ('b987t5cc', 'de', 'Galerie', 'ui'),
  ('b987t5cc', 'fr', 'Galerie', 'ui'),
  ('b987t5cc', 'it', 'Galleria', 'ui'),
  ('b987t5cc', 'no', 'Galleri', 'ui'),
  ('b987t5cc', 'sv', 'Galleri', 'ui'),
  ('bhki1oos', 'en', 'Your location is exclusively used to measure distance to venues and show your location on maps. ', 'ui'),
  ('bhki1oos', 'da', 'Din lokation bruges udelukkende til at vise din afstand til restauranter og vise din placering på kort.', 'ui'),
  ('bhki1oos', 'de', 'Ihr Standort wird ausschließlich dazu verwendet, die Entfernung zu Veranstaltungsorten zu messen und Ihren Standort auf Karten anzuzeigen.', 'ui'),
  ('bhki1oos', 'fr', 'Votre position est exclusivement utilisée pour mesurer la distance par rapport aux lieux et afficher votre position sur les cartes.', 'ui'),
  ('bhki1oos', 'it', 'La tua posizione viene utilizzata esclusivamente per misurare la distanza dai luoghi e mostrarti sulle mappe.', 'ui'),
  ('bhki1oos', 'no', 'Posisjonen din brukes utelukkende til å måle avstand til arenaer og vise posisjonen din på kart.', 'ui'),
  ('bhki1oos', 'sv', 'Din plats används uteslutande för att mäta avstånd till platser och visa din plats på kartor.', 'ui'),
  ('bwvizajd', 'en', 'Show filters', 'ui'),
  ('bwvizajd', 'da', 'Vis filtre', 'ui'),
  ('bwvizajd', 'de', 'Filter anzeigen', 'ui'),
  ('bwvizajd', 'fr', 'Afficher les filtres', 'ui'),
  ('bwvizajd', 'it', 'Mostra filtri', 'ui'),
  ('bwvizajd', 'no', 'Vis filtre', 'ui'),
  ('bwvizajd', 'sv', 'Visa filter', 'ui'),
  ('c0jw62s7', 'en', '• Troubleshooting technical issues', 'ui'),
  ('c669y5g3', 'en', 'Menu', 'ui'),
  ('c669y5g3', 'da', 'Menu', 'ui'),
  ('c669y5g3', 'de', 'Speisekarte', 'ui'),
  ('c669y5g3', 'fr', 'Menu', 'ui'),
  ('c669y5g3', 'it', 'Menu', 'ui'),
  ('c669y5g3', 'no', 'Meny', 'ui'),
  ('c669y5g3', 'sv', 'Meny', 'ui'),
  ('c9r4q0c8', 'en', 'Hours & contact', 'ui'),
  ('c9r4q0c8', 'da', 'Åbningstider m.m.', 'ui'),
  ('c9r4q0c8', 'de', 'Öffnungszeiten & Kontakt', 'ui'),
  ('c9r4q0c8', 'fr', 'Horaires et contact', 'ui'),
  ('c9r4q0c8', 'it', 'Orari e contatti', 'ui'),
  ('c9r4q0c8', 'no', 'Åpningstider og kontakt', 'ui'),
  ('c9r4q0c8', 'sv', 'Öppettider & kontakt', 'ui'),
  ('cjx9drgi', 'en', 'Home', 'ui'),
  ('cjx9drgi', 'da', 'Hjem', 'ui'),
  ('cjx9drgi', 'de', 'Startseite', 'ui'),
  ('cjx9drgi', 'fr', 'Accueil', 'ui'),
  ('cjx9drgi', 'it', 'Home', 'ui'),
  ('cjx9drgi', 'no', 'Hjem', 'ui'),
  ('cjx9drgi', 'sv', 'Hem', 'ui'),
  ('cpiiq0im', 'en', 'Settings & account', 'ui'),
  ('cpiiq0im', 'da', 'Indstillinger og konto', 'ui'),
  ('cpiiq0im', 'de', 'Einstellungen & Konto', 'ui'),
  ('cpiiq0im', 'fr', 'Paramètres et compte', 'ui'),
  ('cpiiq0im', 'it', 'Impostazioni e account', 'ui'),
  ('cpiiq0im', 'no', 'Innstillinger og konto', 'ui'),
  ('cpiiq0im', 'sv', 'Inställningar och konto', 'ui'),
  ('cqerexuq', 'en', 'We may disclose your information only if required to:', 'ui'),
  ('cuy6esxb', 'en', 'Fortsæt på dansk', 'ui'),
  ('cuy6esxb', 'da', 'Fortsæt på dansk', 'ui'),
  ('d2mrwxr4', 'en', 'Continue', 'ui'),
  ('d2mrwxr4', 'da', 'Fortsæt', 'ui'),
  ('d2mrwxr4', 'de', 'Weitermachen', 'ui'),
  ('d2mrwxr4', 'fr', 'Continuer', 'ui'),
  ('d2mrwxr4', 'it', 'Prosegui', 'ui'),
  ('d2mrwxr4', 'no', 'Fortsett', 'ui'),
  ('d2mrwxr4', 'sv', 'Fortsätt', 'ui'),
  ('d952v5y4', 'en', 'Resources', 'ui'),
  ('d952v5y4', 'da', 'Ressourcer', 'ui'),
  ('d952v5y4', 'de', 'Ressourcen', 'ui'),
  ('d952v5y4', 'fr', 'Ressources', 'ui'),
  ('d952v5y4', 'it', 'Risorse', 'ui'),
  ('d952v5y4', 'no', 'Ressurser', 'ui'),
  ('d952v5y4', 'sv', 'Resurser', 'ui'),
  ('d9nsgosc', 'en', 'You can turn off location sharing in your phone''s settings. Tap the button below to continue.', 'ui'),
  ('d9nsgosc', 'da', 'Du kan slå lokationsdeling fra i din telefons indstillinger. Tryk på knappen herunder for at fortsætte.', 'ui'),
  ('d9nsgosc', 'de', 'Du kannst die Standortfreigabe in deinen Telefoneinstellungen ausschalten. Tippe unten auf die Schaltfläche, um fortzufahren.', 'ui'),
  ('d9nsgosc', 'fr', 'Vous pouvez désactiver le partage de position dans les paramètres de votre téléphone. Appuyez sur le bouton ci-dessous pour continuer.', 'ui'),
  ('d9nsgosc', 'it', 'Puoi disattivare la condivisione della posizione nelle impostazioni del tuo telefono. Tocca il pulsante qui sotto per continuare.', 'ui'),
  ('d9nsgosc', 'no', 'Du kan slå av posisjonsdeling i telefonens innstillinger. Trykk på knappen nedenfor for å fortsette.', 'ui'),
  ('d9nsgosc', 'sv', 'Du kan stänga av platsdelning i dina inställningar. Tryck på knappen nedan för att fortsätta.', 'ui'),
  ('dme8eg1t', 'en', 'Contact us', 'ui'),
  ('dme8eg1t', 'da', 'Kontakt os', 'ui'),
  ('dme8eg1t', 'de', 'Kontaktieren Sie uns', 'ui'),
  ('dme8eg1t', 'fr', 'Contactez-nous', 'ui'),
  ('dme8eg1t', 'it', 'Contattaci', 'ui'),
  ('dme8eg1t', 'no', 'Kontakt oss', 'ui'),
  ('dme8eg1t', 'sv', 'Kontakta oss', 'ui'),
  ('dms2jxxk', 'en', 'We do not sell, trade, or share your personal information with third parties. We may share anonymous, aggregated data for analytical purposes.', 'ui'),
  ('dqnzfl3n', 'en', '• Protect our rights or property', 'ui'),
  ('dxjtnh8x', 'en', 'Home', 'ui'),
  ('dxjtnh8x', 'da', 'Hjem', 'ui'),
  ('dxjtnh8x', 'de', 'Startseite', 'ui'),
  ('dxjtnh8x', 'fr', 'Accueil', 'ui'),
  ('dxjtnh8x', 'it', 'Home', 'ui'),
  ('dxjtnh8x', 'no', 'Hjem', 'ui'),
  ('dxjtnh8x', 'sv', 'Hem', 'ui'),
  ('e6ga7u38', 'en', '• All collected data is stored securely using industry-standard encryption', 'ui'),
  ('e9rkrbkn', 'en', 'Home', 'ui'),
  ('e9rkrbkn', 'da', 'Hjem', 'ui'),
  ('e9rkrbkn', 'de', 'Startseite', 'ui'),
  ('e9rkrbkn', 'fr', 'Accueil', 'ui'),
  ('e9rkrbkn', 'it', 'Home', 'ui'),
  ('e9rkrbkn', 'no', 'Hjem', 'ui'),
  ('e9rkrbkn', 'sv', 'Hem', 'ui'),
  ('eekjttrr', 'en', 'Limited Disclosure', 'ui'),
  ('ehwtf95b', 'en', 'Facebook', 'ui'),
  ('ehwtf95b', 'da', 'Facebook', 'ui'),
  ('ehwtf95b', 'de', 'Facebook', 'ui'),
  ('ehwtf95b', 'fr', 'Facebook', 'ui'),
  ('ehwtf95b', 'it', 'Facebook', 'ui'),
  ('ehwtf95b', 'no', 'Facebook', 'ui'),
  ('ehwtf95b', 'sv', 'Facebook', 'ui'),
  ('elv468gp', 'en', 'Currency', 'ui'),
  ('elv468gp', 'da', 'Valuta', 'ui'),
  ('elv468gp', 'de', 'Währung', 'ui'),
  ('elv468gp', 'fr', 'Devise', 'ui'),
  ('elv468gp', 'it', 'Valuta', 'ui'),
  ('elv468gp', 'no', 'Valuta', 'ui'),
  ('elv468gp', 'sv', 'Valuta', 'ui'),
  ('f2nh66ui', 'en', 'If you are in the EU, you have rights under GDPR, including the right to data portability and the right to be forgotten.', 'ui'),
  ('f5zshdrf', 'en', 'Are we missing a place?', 'ui'),
  ('f5zshdrf', 'da', 'Mangler vi et sted?', 'ui'),
  ('f5zshdrf', 'de', 'Fehlt uns ein Ort?', 'ui'),
  ('f5zshdrf', 'fr', 'Il nous manque un endroit ?', 'ui'),
  ('f5zshdrf', 'it', 'Ci manca un posto?', 'ui'),
  ('f5zshdrf', 'no', 'Mangler vi et sted?', 'ui'),
  ('f5zshdrf', 'sv', 'Saknar vi en plats?', 'ui'),
  ('fdh4bmkm', 'en', '•', 'ui'),
  ('fdh4bmkm', 'da', '•', 'ui'),
  ('fdh4bmkm', 'de', '•', 'ui'),
  ('fdh4bmkm', 'fr', '•', 'ui'),
  ('fdh4bmkm', 'it', '•', 'ui'),
  ('fdh4bmkm', 'no', '•', 'ui'),
  ('fdh4bmkm', 'sv', '•', 'ui'),
  ('foeokmwh', 'en', 'Menu', 'ui'),
  ('foeokmwh', 'da', 'Menu', 'ui'),
  ('foeokmwh', 'de', 'Menü', 'ui'),
  ('foeokmwh', 'fr', 'Menu', 'ui'),
  ('foeokmwh', 'it', 'Menu', 'ui'),
  ('foeokmwh', 'no', 'Meny', 'ui'),
  ('foeokmwh', 'sv', 'Meny', 'ui'),
  ('fojleyaf', 'en', 'Location sharing', 'ui'),
  ('fojleyaf', 'da', 'Lokationsdeling', 'ui'),
  ('fojleyaf', 'de', 'Standortfreigabe', 'ui'),
  ('fojleyaf', 'fr', 'Partage de localisation', 'ui'),
  ('fojleyaf', 'it', 'Condivisione della posizione', 'ui'),
  ('fojleyaf', 'no', 'Posisjonsdeling', 'ui'),
  ('fojleyaf', 'sv', 'Platsdelning', 'ui'),
  ('fvn7c52j', 'en', 'Address', 'ui'),
  ('fvn7c52j', 'da', 'Adresse', 'ui'),
  ('fvn7c52j', 'de', 'Adresse', 'ui'),
  ('fvn7c52j', 'fr', 'Adresse', 'ui'),
  ('fvn7c52j', 'it', 'Indirizzo', 'ui'),
  ('fvn7c52j', 'no', 'Adresse', 'ui'),
  ('fvn7c52j', 'sv', 'Adress', 'ui'),
  ('g440jonq', 'en', 'Your search returned no results. Try modifying your search query or select different filters.', 'ui'),
  ('g440jonq', 'da', 'Din søgning gav ingen resultater. Prøv at ændre din søgeforespørgsel eller vælg andre filtre.', 'ui'),
  ('g440jonq', 'de', 'Ihre Suche ergab keine Ergebnisse. Ändern Sie Ihre Suchanfrage oder wählen Sie andere Filter aus.', 'ui'),
  ('g440jonq', 'fr', 'Votre recherche n''a donné aucun résultat. Essayez de modifier votre requête ou de sélectionner d''autres filtres.', 'ui'),
  ('g440jonq', 'it', 'La tua ricerca non ha prodotto risultati. Prova a modificare la query di ricerca o a selezionare filtri diversi.', 'ui'),
  ('g440jonq', 'no', 'Søket ditt ga ingen resultater. Prøv å endre søket eller velg andre filtre.', 'ui'),
  ('g440jonq', 'sv', 'Din sökning gav inga resultat. Försök att ändra din sökfråga eller välj andra filter.', 'ui'),
  ('g6jqo5n0', 'en', 'Make a reservation', 'ui'),
  ('g6jqo5n0', 'da', 'Foretag en reservation', 'ui'),
  ('g6jqo5n0', 'de', 'Reservieren', 'ui'),
  ('g6jqo5n0', 'fr', 'Réserver', 'ui'),
  ('g6jqo5n0', 'it', 'Prenota una prenotazione', 'ui'),
  ('g6jqo5n0', 'no', 'Gjør en reservasjon', 'ui'),
  ('g6jqo5n0', 'sv', 'Gör en reservation', 'ui'),
  ('gaeudpoh', 'en', 'Allow location access to filter by your location.', 'ui'),
  ('gaeudpoh', 'da', 'Giv tilladelse til at appen kan sortere restauranter efter din lokation.', 'ui'),
  ('gaeudpoh', 'de', 'Standortzugriff erlauben, um nach Ihrem Standort zu filtern.', 'ui'),
  ('gaeudpoh', 'fr', 'Autoriser l''accès à la localisation pour filtrer par votre position.', 'ui'),
  ('gaeudpoh', 'it', 'Consenti l''accesso alla posizione per filtrare in base alla tua posizione.', 'ui'),
  ('gaeudpoh', 'no', 'Tillat posisjonstilgang for å filtrere etter posisjonen din.', 'ui'),
  ('gaeudpoh', 'sv', 'Tillåt platstjänster för att filtrera efter din plats.', 'ui'),
  ('gl71ej9n', 'en', 'Your current app language is English.', 'ui'),
  ('gl71ej9n', 'da', 'Dit nuværende appsprog er dansk.', 'ui'),
  ('gl71ej9n', 'de', 'Ihre aktuelle App-Sprache ist Deutsch.', 'ui'),
  ('gl71ej9n', 'fr', 'La langue actuelle de votre application est Français.', 'ui'),
  ('gl71ej9n', 'it', 'La lingua attuale dell''app è Italiano.', 'ui'),
  ('gl71ej9n', 'no', 'Ditt nåværende appspråk er Norsk.', 'ui'),
  ('gl71ej9n', 'sv', 'Ditt nuvarande appspråk är Svenska.', 'ui'),
  ('gne2zp0k', 'en', 'Home', 'ui'),
  ('gne2zp0k', 'da', 'Hjem', 'ui'),
  ('gne2zp0k', 'de', 'Startseite', 'ui'),
  ('gne2zp0k', 'fr', 'Accueil', 'ui'),
  ('gne2zp0k', 'it', 'Home', 'ui'),
  ('gne2zp0k', 'no', 'Hjem', 'ui'),
  ('gne2zp0k', 'sv', 'Hem', 'ui'),
  ('gtmo283r', 'en', 'Privacy policy', 'ui'),
  ('gtmo283r', 'da', 'Privatlivspolitik', 'ui'),
  ('gtmo283r', 'de', 'Datenschutzerklärung', 'ui'),
  ('gtmo283r', 'fr', 'Politique de confidentialité', 'ui'),
  ('gtmo283r', 'it', 'Informativa sulla privacy', 'ui'),
  ('gtmo283r', 'no', 'Personvernerklæring', 'ui'),
  ('gtmo283r', 'sv', 'Integritetspolicy', 'ui'),
  ('hc37a1xq', 'en', 'Home', 'ui'),
  ('hc37a1xq', 'da', 'Hjem', 'ui'),
  ('hc37a1xq', 'de', 'Startseite', 'ui'),
  ('hc37a1xq', 'fr', 'Accueil', 'ui'),
  ('hc37a1xq', 'it', 'Home', 'ui'),
  ('hc37a1xq', 'no', 'Hjem', 'ui'),
  ('hc37a1xq', 'sv', 'Hem', 'ui'),
  ('hjszsd2y', 'en', 'Share feedback', 'ui'),
  ('hjszsd2y', 'da', 'Del feedback', 'ui'),
  ('hjszsd2y', 'de', 'Feedback teilen', 'ui'),
  ('hjszsd2y', 'fr', 'Partagez vos commentaires', 'ui'),
  ('hjszsd2y', 'it', 'Condividi il feedback', 'ui'),
  ('hjszsd2y', 'no', 'Del tilbakemeldinger', 'ui'),
  ('hjszsd2y', 'sv', 'Dela feedback', 'ui'),
  ('i31p0kb6', 'en', 'If you have questions about this Privacy Policy or our practices, please contact us at:\n\nAndreas M. Strandgaard\nandreasms@hey.com\n+4540525072', 'ui'),
  ('i39eb4yz', 'en', 'View on Instagram', 'ui'),
  ('i39eb4yz', 'da', 'Se på Instagram', 'ui'),
  ('i39eb4yz', 'de', 'Auf Instagram ansehen', 'ui'),
  ('i39eb4yz', 'fr', 'Voir sur Instagram', 'ui'),
  ('i39eb4yz', 'it', 'Guarda su Instagram', 'ui'),
  ('i39eb4yz', 'no', 'Se på Instagram', 'ui'),
  ('i39eb4yz', 'sv', 'Visa på Instagram', 'ui'),
  ('i6lhb9qo', 'en', '• Log data (app interactions, error reports)', 'ui'),
  ('ikkj0kou', 'en', '• Location data (only when you use location-based features) ', 'ui'),
  ('iucaz964', 'en', 'Your location is exclusively used to measure distance to venues and show your location on maps. ', 'ui'),
  ('iucaz964', 'da', 'Din lokation bruges udelukkende til at vise din afstand til restauranter og vise din placering på kort.', 'ui'),
  ('iucaz964', 'de', 'Ihr Standort wird ausschließlich dazu verwendet, die Entfernung zu Veranstaltungsorten zu messen und Ihren Standort auf Karten anzuzeigen.', 'ui'),
  ('iucaz964', 'fr', 'Votre position est exclusivement utilisée pour mesurer la distance par rapport aux lieux et afficher votre position sur les cartes.', 'ui'),
  ('iucaz964', 'it', 'La tua posizione viene utilizzata esclusivamente per misurare la distanza dai luoghi e mostrarti sulle mappe.', 'ui'),
  ('iucaz964', 'no', 'Posisjonen din brukes utelukkende til å måle avstand til arenaer og vise posisjonen din på kart.', 'ui'),
  ('iucaz964', 'sv', 'Din plats används uteslutande för att mäta avstånd till platser och visa din plats på kartor.', 'ui'),
  ('iy4maakr', 'en', 'Payment options', 'ui'),
  ('iy4maakr', 'da', 'Betalingsmuligheder', 'ui'),
  ('iy4maakr', 'de', 'Zahlungsmöglichkeiten', 'ui'),
  ('iy4maakr', 'fr', 'Options de paiement', 'ui'),
  ('iy4maakr', 'it', 'Opzioni di pagamento', 'ui'),
  ('iy4maakr', 'no', 'Betalingsmåter', 'ui'),
  ('iy4maakr', 'sv', 'Betalsätt', 'ui'),
  ('j4021elv', 'en', 'Region-Specific Rights', 'ui'),
  ('jizrgy8p', 'en', '• Receive a copy of your data', 'ui'),
  ('k1c3fupg', 'en', 'Location sharing', 'ui'),
  ('k1c3fupg', 'da', 'Lokationsdeling', 'ui'),
  ('k1c3fupg', 'de', 'Standortfreigabe', 'ui'),
  ('k1c3fupg', 'fr', 'Partage de localisation', 'ui'),
  ('k1c3fupg', 'it', 'Condivisione della posizione', 'ui'),
  ('k1c3fupg', 'no', 'Posisjonsdeling', 'ui'),
  ('k1c3fupg', 'sv', 'Platsdelning', 'ui'),
  ('k1zbavsf', 'en', '•', 'ui'),
  ('k1zbavsf', 'da', '•', 'ui'),
  ('k1zbavsf', 'de', '•', 'ui'),
  ('k1zbavsf', 'fr', '•', 'ui'),
  ('k1zbavsf', 'it', '•', 'ui'),
  ('k1zbavsf', 'no', '•', 'ui'),
  ('k1zbavsf', 'sv', '•', 'ui'),
  ('kdtohmum', 'en', '• Request deletion of your data', 'ui'),
  ('knwrqf3u', 'en', 'View all images', 'ui'),
  ('knwrqf3u', 'da', 'Se alle billeder', 'ui'),
  ('knwrqf3u', 'de', 'Alle Bilder anzeigen', 'ui'),
  ('knwrqf3u', 'fr', 'Voir toutes les images', 'ui'),
  ('knwrqf3u', 'it', 'Visualizza tutte le immagini', 'ui'),
  ('knwrqf3u', 'no', 'Se alle bildene', 'ui'),
  ('knwrqf3u', 'sv', 'Visa alla bilder', 'ui'),
  ('l5n7zt4y', 'en', 'View on full page', 'ui'),
  ('l5n7zt4y', 'da', 'Vis på hel side', 'ui'),
  ('l5n7zt4y', 'de', 'Menü in Vollbildansicht', 'ui'),
  ('l5n7zt4y', 'fr', 'Afficher en pleine page', 'ui'),
  ('l5n7zt4y', 'it', 'Visualizza a pagina intera', 'ui'),
  ('l5n7zt4y', 'no', 'Vis på full side', 'ui'),
  ('l5n7zt4y', 'sv', 'Visa på hel sida', 'ui'),
  ('ldrdlmaf', 'en', '• Prevent fraud or security issues', 'ui'),
  ('lhkz1jbd', 'en', '• Technical information necessary for app updates and maintenance', 'ui'),
  ('ljnuiq34', 'en', 'Features, services & amenities', 'ui'),
  ('ljnuiq34', 'da', 'Faciliteter og services', 'ui'),
  ('ljnuiq34', 'de', 'Ausstattung & Services', 'ui'),
  ('ljnuiq34', 'fr', ' Services et équipements', 'ui'),
  ('ljnuiq34', 'it', 'Servizi e comfort', 'ui'),
  ('ljnuiq34', 'no', 'Fasiliteter og tjenester', 'ui'),
  ('ljnuiq34', 'sv', 'Faciliteter och service', 'ui'),
  ('lup5v7ii', 'en', 'Select your preferred language and currency to use in the app. ', 'ui'),
  ('lup5v7ii', 'da', 'Vælg foretrukket sprog og valuta.', 'ui'),
  ('lup5v7ii', 'de', 'Bevorzugte Sprache und Währung wählen.', 'ui'),
  ('lup5v7ii', 'fr', 'Choisissez votre langue et devise.', 'ui'),
  ('lup5v7ii', 'it', 'Seleziona lingua e valuta.', 'ui'),
  ('lup5v7ii', 'no', 'Velg språk og valuta.', 'ui'),
  ('lup5v7ii', 'sv', 'Välj språk och valuta.', 'ui'),
  ('m2phxcsi', 'en', 'Under California law, you have specific rights regarding your personal information. Please contact us for more details.', 'ui'),
  ('m4kntw8r', 'en', 'Search', 'ui'),
  ('m4kntw8r', 'da', 'Søg', 'ui'),
  ('m4kntw8r', 'de', 'Suche', 'ui'),
  ('m4kntw8r', 'fr', 'Recherche', 'ui'),
  ('m4kntw8r', 'it', 'Ricerca', 'ui'),
  ('m4kntw8r', 'no', 'Søk', 'ui'),
  ('m4kntw8r', 'sv', 'Söka', 'ui'),
  ('ma3urnt3', 'en', 'Your rights', 'ui'),
  ('n4pzujqg', 'en', 'Prices will be shown in ', 'ui'),
  ('n4pzujqg', 'da', 'Priser vil blive vist i ', 'ui'),
  ('n4pzujqg', 'de', 'Preise werden angezeigt in ', 'ui'),
  ('n4pzujqg', 'fr', 'Prix seront affichés en ', 'ui'),
  ('n4pzujqg', 'it', 'Prezzi saranno mostrati in ', 'ui'),
  ('n4pzujqg', 'no', 'Priser vil bli vist i ', 'ui'),
  ('n4pzujqg', 'sv', 'Priser kommer att visas i ', 'ui'),
  ('n5kw731s', 'en', 'Language & currency', 'ui'),
  ('n5kw731s', 'da', 'Sprog og valuta', 'ui'),
  ('n5kw731s', 'de', 'Sprache und Währung', 'ui'),
  ('n5kw731s', 'fr', 'Langue et devise', 'ui'),
  ('n5kw731s', 'it', 'Lingua e valuta', 'ui'),
  ('n5kw731s', 'no', 'Språk og valuta', 'ui'),
  ('n5kw731s', 'sv', 'Språk och valuta', 'ui'),
  ('ncr4ao4z', 'en', 'We use the collected information solely for:', 'ui'),
  ('nd4d9n42', 'en', 'Phone number', 'ui'),
  ('nd4d9n42', 'da', 'Telefonnummer', 'ui'),
  ('nd4d9n42', 'de', 'Telefonnummer', 'ui'),
  ('nd4d9n42', 'fr', 'Numéro de téléphone', 'ui'),
  ('nd4d9n42', 'it', 'Numero di telefono', 'ui'),
  ('nd4d9n42', 'no', 'Telefonnummer', 'ui'),
  ('nd4d9n42', 'sv', 'Telefonnummer', 'ui'),
  ('ndthifkd', 'en', '•', 'ui'),
  ('ndthifkd', 'da', '•', 'ui'),
  ('ndthifkd', 'de', '•', 'ui'),
  ('ndthifkd', 'fr', '•', 'ui'),
  ('ndthifkd', 'it', '•', 'ui'),
  ('ndthifkd', 'no', '•', 'ui'),
  ('ndthifkd', 'sv', '•', 'ui'),
  ('nhhhl06z', 'en', 'View on Facebook', 'ui'),
  ('nhhhl06z', 'da', 'Se på Facebook', 'ui'),
  ('nhhhl06z', 'de', 'Auf Facebook ansehen', 'ui'),
  ('nhhhl06z', 'fr', 'Voir sur Facebook', 'ui'),
  ('nhhhl06z', 'it', 'Visualizza su Facebook', 'ui'),
  ('nhhhl06z', 'no', 'Vis på Facebook', 'ui'),
  ('nhhhl06z', 'sv', 'Visa på Facebook', 'ui'),
  ('nmii0gwo', 'en', 'We may update this Privacy Policy periodically. We will notify you of any material changes through the app or via email.', 'ui'),
  ('nmk8r6o5', 'en', 'Vælg mellem:', 'ui'),
  ('nrkrbwjr', 'en', 'Home', 'ui'),
  ('nrkrbwjr', 'da', 'Hjem', 'ui'),
  ('nrkrbwjr', 'de', 'Startseite', 'ui'),
  ('nrkrbwjr', 'fr', 'Accueil', 'ui'),
  ('nrkrbwjr', 'it', 'Home', 'ui'),
  ('nrkrbwjr', 'no', 'Hjem', 'ui'),
  ('nrkrbwjr', 'sv', 'Hem', 'ui'),
  ('odbjrzjs', 'en', 'Hide filters', 'ui'),
  ('odbjrzjs', 'da', 'Skjul filtre', 'ui'),
  ('odbjrzjs', 'de', 'Filter ausblenden', 'ui'),
  ('odbjrzjs', 'fr', 'Masquer les filtres', 'ui'),
  ('odbjrzjs', 'it', 'Nascondi filtri', 'ui'),
  ('odbjrzjs', 'no', 'Skjul filtre', 'ui'),
  ('odbjrzjs', 'sv', 'Dölj filter', 'ui'),
  ('oimmokml', 'en', 'Last updated on November 12, 2024', 'ui'),
  ('opycnrvy', 'en', 'App setup', 'ui'),
  ('opycnrvy', 'da', 'Opsætning', 'ui'),
  ('opycnrvy', 'de', 'Einrichtung', 'ui'),
  ('opycnrvy', 'fr', 'Configuration', 'ui'),
  ('opycnrvy', 'it', 'Configurazione', 'ui'),
  ('opycnrvy', 'no', 'Oppsett', 'ui'),
  ('opycnrvy', 'sv', 'Inställningar', 'ui'),
  ('p2440u1x', 'en', 'Additional information', 'ui'),
  ('p2440u1x', 'da', 'Yderligere information', 'ui'),
  ('p2440u1x', 'de', 'Weitere Informationen', 'ui'),
  ('p2440u1x', 'fr', 'Informations Complémentaires', 'ui'),
  ('p2440u1x', 'it', 'Informazioni aggiuntive', 'ui'),
  ('p2440u1x', 'no', 'Tilleggsinformasjon', 'ui'),
  ('p2440u1x', 'sv', 'Ytterligare information', 'ui'),
  ('p6psr93i', 'en', 'Home', 'ui'),
  ('p6psr93i', 'da', 'Hjem', 'ui'),
  ('p6psr93i', 'de', 'Startseite', 'ui'),
  ('p6psr93i', 'fr', 'Accueil', 'ui'),
  ('p6psr93i', 'it', 'Home', 'ui'),
  ('p6psr93i', 'no', 'Hjem', 'ui'),
  ('p6psr93i', 'sv', 'Hem', 'ui'),
  ('pb7qrt34', 'en', 'Reach out', 'ui'),
  ('pb7qrt34', 'da', 'Kontakt os', 'ui'),
  ('pb7qrt34', 'de', 'Kontaktieren Sie uns', 'ui'),
  ('pb7qrt34', 'fr', 'Contactez-nous', 'ui'),
  ('pb7qrt34', 'it', 'Contattaci', 'ui'),
  ('pb7qrt34', 'no', 'Kontakt oss', 'ui'),
  ('pb7qrt34', 'sv', 'Kontakta oss', 'ui'),
  ('phfch9og', 'en', 'Set your preferred language for the app', 'ui'),
  ('phfch9og', 'da', 'Indstil dit foretrukne sprog til appen', 'ui'),
  ('phfch9og', 'de', 'Stellen Sie Ihre bevorzugte Sprache für die App ein', 'ui'),
  ('phfch9og', 'fr', 'Définissez votre langue préférée pour l''application', 'ui'),
  ('phfch9og', 'it', 'Imposta la lingua preferita per l''app', 'ui'),
  ('phfch9og', 'no', 'Angi ønsket språk for appen', 'ui'),
  ('phfch9og', 'sv', 'Ställ in ditt önskade språk för appen', 'ui'),
  ('py5t78tb', 'da', 'Fejl', 'ui'),
  ('q6agbobw', 'en', 'Contact us', 'ui'),
  ('q6agbobw', 'da', 'Kontakt os', 'ui'),
  ('q6agbobw', 'de', 'Kontaktieren Sie uns', 'ui'),
  ('q6agbobw', 'fr', 'Contactez-nous', 'ui'),
  ('q6agbobw', 'it', 'Contattaci', 'ui'),
  ('q6agbobw', 'no', 'Kontakt oss', 'ui'),
  ('q6agbobw', 'sv', 'Kontakta oss', 'ui'),
  ('q77esk10', 'en', 'Allergens', 'ui'),
  ('q77esk10', 'da', 'Allergener', 'ui'),
  ('q77esk10', 'de', 'Allergene', 'ui'),
  ('q77esk10', 'fr', 'Allergènes', 'ui'),
  ('q77esk10', 'it', 'Allergeni', 'ui'),
  ('q77esk10', 'no', 'Allergener', 'ui'),
  ('q77esk10', 'sv', 'Allergener', 'ui'),
  ('qc25om4m', 'en', 'Closed', 'ui'),
  ('qc25om4m', 'da', 'Lukket', 'ui'),
  ('qc25om4m', 'de', 'Zu', 'ui'),
  ('qc25om4m', 'fr', 'Fermé', 'ui'),
  ('qc25om4m', 'it', 'Chiuso', 'ui'),
  ('qc25om4m', 'no', 'Lukket', 'ui'),
  ('qc25om4m', 'sv', 'Stängd', 'ui'),
  ('qque50y7', 'en', '• Improving app performance and user experience', 'ui'),
  ('qsoa8t7r', 'en', 'We collect only the following information that is strictly necessary for the app to function:', 'ui'),
  ('rct7k6pr', 'en', 'Language & currency', 'ui'),
  ('rct7k6pr', 'da', 'Sprog og valuta', 'ui'),
  ('rct7k6pr', 'de', 'Sprache und Währung', 'ui'),
  ('rct7k6pr', 'fr', 'Langue et devise', 'ui'),
  ('rct7k6pr', 'it', 'Lingua e valuta', 'ui'),
  ('rct7k6pr', 'no', 'Språk og valuta', 'ui'),
  ('rct7k6pr', 'sv', 'Språk och valuta', 'ui'),
  ('rpsnluih', 'en', '• We implement appropriate technical measures to protect your information', 'ui'),
  ('ry4h2eyu', 'en', 'Contact Us', 'ui'),
  ('s0a1ukr7', 'en', 'Contact information', 'ui'),
  ('s0a1ukr7', 'da', 'Kontaktoplysninger', 'ui'),
  ('s0a1ukr7', 'de', 'Kontaktinformationen', 'ui'),
  ('s0a1ukr7', 'fr', 'Coordonnées', 'ui'),
  ('s0a1ukr7', 'it', 'Informazioni sui contatti', 'ui'),
  ('s0a1ukr7', 'no', 'Kontaktinformasjon', 'ui'),
  ('s0a1ukr7', 'sv', 'Kontaktinformation', 'ui'),
  ('s3movlvc', 'en', 'Language', 'ui'),
  ('s3movlvc', 'da', 'Sprog', 'ui'),
  ('s3movlvc', 'de', 'Sprache', 'ui'),
  ('s3movlvc', 'fr', 'Langue', 'ui'),
  ('s3movlvc', 'it', 'Lingua', 'ui'),
  ('s3movlvc', 'no', 'Språk', 'ui'),
  ('s3movlvc', 'sv', 'Språk', 'ui'),
  ('s5ln0zny', 'en', 'Essential App Functionality Data', 'ui'),
  ('sesu8r6a', 'en', 'Home', 'ui'),
  ('sesu8r6a', 'da', 'Hjem', 'ui'),
  ('sesu8r6a', 'de', 'Startseite', 'ui'),
  ('sesu8r6a', 'fr', 'Accueil', 'ui'),
  ('sesu8r6a', 'it', 'Home', 'ui'),
  ('sesu8r6a', 'no', 'Hjem', 'ui'),
  ('sesu8r6a', 'sv', 'Hem', 'ui'),
  ('sgpknl00', 'en', 'Last brought up to date on ', 'ui'),
  ('sgpknl00', 'da', 'Sidst ajourført den ', 'ui'),
  ('sgpknl00', 'de', 'Zuletzt aktualisiert am ', 'ui'),
  ('sgpknl00', 'fr', 'Dernière mise à jour ', 'ui'),
  ('sgpknl00', 'it', 'Ultimo aggiornamento ', 'ui'),
  ('sgpknl00', 'no', 'Sist ajourført ', 'ui'),
  ('sgpknl00', 'sv', 'Senast ajourförd ', 'ui'),
  ('t8dwyvby', 'en', 'Our app does not knowingly collect information from children under 18. If you believe we have inadvertently collected such information, please contact us to have it removed.', 'ui'),
  ('tht0e2um', 'en', 'To turn on location sharing, tap the button below and grant permission in the pop-up.', 'ui'),
  ('tht0e2um', 'da', 'For at aktivere deling af lokation skal du trykke på knappen nedenfor og give tilladelse i pop op-vinduet.', 'ui'),
  ('tht0e2um', 'de', 'Um die Standortfreigabe zu aktivieren, tippen Sie auf die Schaltfläche unten und erteilen Sie die Berechtigung im Pop-up-Fenster.', 'ui'),
  ('tht0e2um', 'fr', 'Pour activer le partage de position, appuyez sur le bouton ci-dessous et accordez l''autorisation dans la fenêtre contextuelle.', 'ui'),
  ('tht0e2um', 'it', 'Per attivare la condivisione della posizione, tocca il pulsante qui sotto e concedi l''autorizzazione nel pop-up.', 'ui'),
  ('tht0e2um', 'no', 'For å slå på posisjonsdeling, trykk på knappen nedenfor og gi tillatelse i popup-vinduet.', 'ui'),
  ('tht0e2um', 'sv', 'För att aktivera platsdelning, tryck på knappen nedan och ge behörighet i popup-fönstret.', 'ui'),
  ('tqjzlyzs', 'en', 'Home', 'ui'),
  ('tqjzlyzs', 'da', 'Hjem', 'ui'),
  ('tqjzlyzs', 'de', 'Startseite', 'ui'),
  ('tqjzlyzs', 'fr', 'Accueil', 'ui'),
  ('tqjzlyzs', 'it', 'Home', 'ui'),
  ('tqjzlyzs', 'no', 'Hjem', 'ui'),
  ('tqjzlyzs', 'sv', 'Hem', 'ui'),
  ('ttf99xss', 'en', 'Dietary preferences and restrictions', 'ui'),
  ('ttf99xss', 'da', 'Kostpræferencer- og restriktioner', 'ui'),
  ('ttf99xss', 'de', 'Ernährungspräferenzen und -einschränkungen', 'ui'),
  ('ttf99xss', 'fr', 'Préférences et restrictions alimentaires', 'ui'),
  ('ttf99xss', 'it', 'Preferenze e restrizioni dietetiche', 'ui'),
  ('ttf99xss', 'no', 'Kostholdspreferanser og restriksjoner', 'ui'),
  ('ttf99xss', 'sv', 'Kostpreferenser och restriktioner', 'ui'),
  ('tz6eo1fd', 'en', 'Our app may collect certain information automatically, including:', 'ui'),
  ('u0wnvdeg', 'en', 'Turn on location sharing', 'ui'),
  ('u0wnvdeg', 'da', 'Slå lokationsdeling til', 'ui'),
  ('u0wnvdeg', 'de', 'Aktivieren Sie die Standortfreigabe', 'ui'),
  ('u0wnvdeg', 'fr', 'Activer le partage de position', 'ui'),
  ('u0wnvdeg', 'it', 'Attiva la condivisione della posizione', 'ui'),
  ('u0wnvdeg', 'no', 'Slå på posisjonsdeling', 'ui'),
  ('u0wnvdeg', 'sv', 'Aktivera platsdelning', 'ui'),
  ('u0z37ztz', 'en', 'Privacy Policy', 'ui'),
  ('u3zvsnz8', 'en', 'Opening hours & contact', 'ui'),
  ('u3zvsnz8', 'da', 'Åbningstider og kontakt', 'ui'),
  ('u3zvsnz8', 'de', 'Zeiten & Kontakt', 'ui'),
  ('u3zvsnz8', 'fr', 'Horaires & contact', 'ui'),
  ('u3zvsnz8', 'it', 'Orari & contatti', 'ui'),
  ('u3zvsnz8', 'no', 'Åpningstider og kontakt', 'ui'),
  ('u3zvsnz8', 'sv', 'Öppettider och kontakt', 'ui'),
  ('uz83tnpj', 'en', 'Share feedback', 'ui'),
  ('uz83tnpj', 'da', 'Del feedback', 'ui'),
  ('uz83tnpj', 'de', 'Feedback teilen', 'ui'),
  ('uz83tnpj', 'fr', 'Partagez vos commentaires', 'ui'),
  ('uz83tnpj', 'it', 'Condividi il feedback', 'ui'),
  ('uz83tnpj', 'no', 'Gi tilbakemelding', 'ui'),
  ('uz83tnpj', 'sv', 'Dela feedback', 'ui'),
  ('v1z4dvep', 'en', 'Opening hours', 'ui'),
  ('v1z4dvep', 'da', 'Åbningstider', 'ui'),
  ('v1z4dvep', 'de', 'Öffnungszeiten', 'ui'),
  ('v1z4dvep', 'fr', 'Horaires d''ouverture', 'ui'),
  ('v1z4dvep', 'it', 'Orari di apertura', 'ui'),
  ('v1z4dvep', 'no', 'Åpningstider', 'ui'),
  ('v1z4dvep', 'sv', 'Öppettider', 'ui'),
  ('v7mckwj4', 'en', 'Button', 'ui'),
  ('vtn0ht6v', 'en', 'Home', 'ui'),
  ('vtn0ht6v', 'da', 'Hjem', 'ui'),
  ('vtn0ht6v', 'de', 'Startseite', 'ui'),
  ('vtn0ht6v', 'fr', 'Accueil', 'ui'),
  ('vtn0ht6v', 'it', 'Home', 'ui'),
  ('vtn0ht6v', 'no', 'Hjem', 'ui'),
  ('vtn0ht6v', 'sv', 'Hem', 'ui'),
  ('w2bisy1y', 'en', 'Set language', 'ui'),
  ('w2bisy1y', 'da', 'Vælg sprog', 'ui'),
  ('wemfo75s', 'en', 'View on map', 'ui'),
  ('wemfo75s', 'da', 'Se på kort', 'ui'),
  ('wemfo75s', 'de', 'Auf der Karte anzeigen', 'ui'),
  ('wemfo75s', 'fr', 'Voir sur la carte', 'ui'),
  ('wemfo75s', 'it', 'Visualizza sulla mappa', 'ui'),
  ('wemfo75s', 'no', 'Vis på kart', 'ui'),
  ('wemfo75s', 'sv', 'Visa på karta', 'ui'),
  ('wfjs3k4y', 'en', '• Providing and maintaining the app''s core functionality', 'ui'),
  ('wgnx5mvk', 'en', 'Show filters', 'ui'),
  ('wgnx5mvk', 'da', 'Vis filtre', 'ui'),
  ('wgnx5mvk', 'de', 'Filter anzeigen', 'ui'),
  ('wgnx5mvk', 'fr', 'Afficher les filtres', 'ui'),
  ('wgnx5mvk', 'it', 'Mostra filtri', 'ui'),
  ('wgnx5mvk', 'no', 'Vis filtre', 'ui'),
  ('wgnx5mvk', 'sv', 'Visa filter', 'ui'),
  ('wxwsnvy9', 'en', '• Ensuring app security and stability', 'ui'),
  ('x5kyid2g', 'en', '• App usage data (such as app performance metrics and crash reports)', 'ui'),
  ('xl0f1tfz', 'en', 'You have the right to:', 'ui'),
  ('xn0d16r3', 'en', 'Search', 'ui'),
  ('xn0d16r3', 'da', 'Søg', 'ui'),
  ('xn0d16r3', 'de', 'Suche', 'ui'),
  ('xn0d16r3', 'fr', 'Recherche', 'ui'),
  ('xn0d16r3', 'it', 'Cerca', 'ui'),
  ('xn0d16r3', 'no', 'Søk', 'ui'),
  ('xn0d16r3', 'sv', 'Sök', 'ui'),
  ('y0gzdnsp', 'en', 'Set your preferred currency for the app', 'ui'),
  ('y0gzdnsp', 'da', 'Indstil din foretrukne valuta for appen', 'ui'),
  ('y0gzdnsp', 'de', 'Legen Sie Ihre bevorzugte Währung für die App fest', 'ui'),
  ('y0gzdnsp', 'fr', 'Définissez votre devise préférée pour l''application', 'ui'),
  ('y0gzdnsp', 'it', 'Imposta la valuta preferita per l''app', 'ui'),
  ('y0gzdnsp', 'no', 'Angi din foretrukne valuta for appen', 'ui'),
  ('y0gzdnsp', 'sv', 'Ställ in din önskade valuta för appen', 'ui'),
  ('ykne5sdr', 'en', 'Account', 'ui'),
  ('ykne5sdr', 'da', 'Konto', 'ui'),
  ('ykne5sdr', 'de', 'Konto', 'ui'),
  ('ykne5sdr', 'fr', 'Compte', 'ui'),
  ('ykne5sdr', 'it', 'Account', 'ui'),
  ('ykne5sdr', 'no', 'Konto', 'ui'),
  ('ykne5sdr', 'sv', 'Konto', 'ui'),
  ('z1v9fk1m', 'en', 'Location sharing is turned on', 'ui'),
  ('z1v9fk1m', 'da', 'Lokationsdeling er slået til', 'ui'),
  ('z1v9fk1m', 'de', 'Die Standortfreigabe ist aktiviert', 'ui'),
  ('z1v9fk1m', 'fr', 'Le partage de position est activé', 'ui'),
  ('z1v9fk1m', 'it', 'La condivisione della posizione è attivata', 'ui'),
  ('z1v9fk1m', 'no', 'Posisjonsdeling er slått på', 'ui'),
  ('z1v9fk1m', 'sv', 'Platsdelning är aktiverad', 'ui'),
  ('z32g0m7g', 'en', 'Email', 'ui'),
  ('z32g0m7g', 'da', 'E-mail', 'ui'),
  ('z32g0m7g', 'de', 'E-Mail', 'ui'),
  ('z32g0m7g', 'fr', 'E-mail', 'ui'),
  ('z32g0m7g', 'it', 'E-mail', 'ui'),
  ('z32g0m7g', 'no', 'E-post', 'ui'),
  ('z32g0m7g', 'sv', 'E-post', 'ui'),
  ('z6e1v2g7', 'en', 'Go out, your way. ', 'ui'),
  ('z6e1v2g7', 'da', 'Go out, your way. ', 'ui'),
  ('z6e1v2g7', 'de', 'Go out, your way. ', 'ui'),
  ('z6e1v2g7', 'fr', 'Go out, your way.', 'ui'),
  ('z6e1v2g7', 'it', 'Go out, your way. ', 'ui'),
  ('z6e1v2g7', 'no', 'Go out, your way. ', 'ui'),
  ('z6e1v2g7', 'sv', 'Go out, your way. ', 'ui'),
  ('zaws00rk', 'en', 'Reservation', 'ui'),
  ('zaws00rk', 'da', 'Reservation', 'ui'),
  ('zaws00rk', 'de', 'Reservierung', 'ui'),
  ('zaws00rk', 'fr', 'Réservation', 'ui'),
  ('zaws00rk', 'it', 'Prenotazione', 'ui'),
  ('zaws00rk', 'no', 'Reservasjon', 'ui'),
  ('zaws00rk', 'sv', 'Bokning', 'ui'),
  ('zivoov4e', 'en', 'In order to search for nearby places, the app needs to use your location', 'ui'),
  ('zlgcyzrw', 'en', 'Payment options', 'ui'),
  ('zlgcyzrw', 'da', 'Betalingsmuligheder', 'ui'),
  ('zlgcyzrw', 'de', 'Zahlungsmöglichkeiten', 'ui'),
  ('zlgcyzrw', 'fr', 'Options de paiement', 'ui'),
  ('zlgcyzrw', 'it', 'Opzioni di pagamento', 'ui'),
  ('zlgcyzrw', 'no', 'Betalingsmåter', 'ui'),
  ('zlgcyzrw', 'sv', 'Betalsätt', 'ui'),
  ('zuav7wui', 'en', 'Home', 'ui'),
  ('zuav7wui', 'da', 'Hjem', 'ui'),
  ('zuav7wui', 'de', 'Startseite', 'ui'),
  ('zuav7wui', 'fr', 'Accueil', 'ui'),
  ('zuav7wui', 'it', 'Home', 'ui'),
  ('zuav7wui', 'no', 'Hjem', 'ui'),
  ('zuav7wui', 'sv', 'Hem', 'ui');

-- ============================================================
-- Phase 7 New Keys (38 keys - descriptive names)
-- These were added during Phase 7 but not yet in Supabase
-- ============================================================

INSERT INTO ui_translations (translation_key, language_code, translation_text, category)
VALUES
  ('about_description_label', 'en', 'Description', 'ui'),
  ('about_description_label', 'da', 'Beskrivelse', 'ui'),
  ('about_description_label', 'de', 'Beschreibung', 'ui'),
  ('about_description_label', 'fr', 'Description', 'ui'),
  ('about_description_label', 'it', 'Descrizione', 'ui'),
  ('about_description_label', 'no', 'Beskrivelse', 'ui'),
  ('about_description_label', 'sv', 'Beskrivning', 'ui'),
  ('about_payment_options_label', 'en', 'Payment Options', 'ui'),
  ('about_payment_options_label', 'da', 'Betalingsmuligheder', 'ui'),
  ('about_payment_options_label', 'de', 'Zahlungsoptionen', 'ui'),
  ('about_payment_options_label', 'fr', 'Options de paiement', 'ui'),
  ('about_payment_options_label', 'it', 'Opzioni di pagamento', 'ui'),
  ('about_payment_options_label', 'no', 'Betalingsalternativer', 'ui'),
  ('about_payment_options_label', 'sv', 'Betalningsalternativ', 'ui'),
  ('about_report_incorrect_info', 'en', 'Report incorrect information', 'ui'),
  ('about_report_incorrect_info', 'da', 'Rapporter ukorrekte oplysninger', 'ui'),
  ('about_report_incorrect_info', 'de', 'Falsche Informationen melden', 'ui'),
  ('about_report_incorrect_info', 'fr', 'Signaler des informations incorrectes', 'ui'),
  ('about_report_incorrect_info', 'it', 'Segnala informazioni errate', 'ui'),
  ('about_report_incorrect_info', 'no', 'Rapporter feil informasjon', 'ui'),
  ('about_report_incorrect_info', 'sv', 'Rapportera felaktig information', 'ui'),
  ('business_not_found', 'en', 'Business not found', 'ui'),
  ('business_not_found', 'da', 'Virksomhed ikke fundet', 'ui'),
  ('business_not_found', 'de', 'Geschäft nicht gefunden', 'ui'),
  ('business_not_found', 'fr', 'Établissement non trouvé', 'ui'),
  ('business_not_found', 'it', 'Attività non trovata', 'ui'),
  ('business_not_found', 'no', 'Bedrift ikke funnet', 'ui'),
  ('business_not_found', 'sv', 'Företag hittades inte', 'ui'),
  ('currency_chf_cap', 'en', 'Swiss Franc', 'ui'),
  ('currency_chf_cap', 'da', 'Schweiziske franc', 'ui'),
  ('currency_chf_cap', 'de', 'Schweizer Franken', 'ui'),
  ('currency_chf_cap', 'fr', 'Franc suisse', 'ui'),
  ('currency_chf_cap', 'it', 'Franco svizzero', 'ui'),
  ('currency_chf_cap', 'no', 'Sveitsiske franc', 'ui'),
  ('currency_chf_cap', 'sv', 'Schweiziska franc', 'ui'),
  ('currency_cny_cap', 'en', 'Chinese Yuan', 'ui'),
  ('currency_cny_cap', 'da', 'Kinesiske yuan', 'ui'),
  ('currency_cny_cap', 'de', 'Chinesischer Yuan', 'ui'),
  ('currency_cny_cap', 'fr', 'Yuan chinois', 'ui'),
  ('currency_cny_cap', 'it', 'Yuan cinese', 'ui'),
  ('currency_cny_cap', 'no', 'Kinesiske yuan', 'ui'),
  ('currency_cny_cap', 'sv', 'Kinesiska yuan', 'ui'),
  ('currency_jpy_cap', 'en', 'Japanese Yen', 'ui'),
  ('currency_jpy_cap', 'da', 'Japanske yen', 'ui'),
  ('currency_jpy_cap', 'de', 'Japanischer Yen', 'ui'),
  ('currency_jpy_cap', 'fr', 'Yen japonais', 'ui'),
  ('currency_jpy_cap', 'it', 'Yen giapponese', 'ui'),
  ('currency_jpy_cap', 'no', 'Japanske yen', 'ui'),
  ('currency_jpy_cap', 'sv', 'Japanska yen', 'ui'),
  ('currency_pln_cap', 'en', 'Polish Złoty', 'ui'),
  ('currency_pln_cap', 'da', 'Polske złoty', 'ui'),
  ('currency_pln_cap', 'de', 'Polnischer Złoty', 'ui'),
  ('currency_pln_cap', 'fr', 'Złoty polonais', 'ui'),
  ('currency_pln_cap', 'it', 'Złoty polacco', 'ui'),
  ('currency_pln_cap', 'no', 'Polske złoty', 'ui'),
  ('currency_pln_cap', 'sv', 'Polska złoty', 'ui'),
  ('currency_uah_cap', 'en', 'Ukrainian Hryvnia', 'ui'),
  ('currency_uah_cap', 'da', 'Ukrainske hryvnia', 'ui'),
  ('currency_uah_cap', 'de', 'Ukrainische Hrywnja', 'ui'),
  ('currency_uah_cap', 'fr', 'Hryvnia ukrainienne', 'ui'),
  ('currency_uah_cap', 'it', 'Grivna ucraina', 'ui'),
  ('currency_uah_cap', 'no', 'Ukrainske hryvnia', 'ui'),
  ('currency_uah_cap', 'sv', 'Ukrainska hryvnia', 'ui'),
  ('erroneous_info_error_network', 'en', 'Network error. Please check your connection.', 'ui'),
  ('erroneous_info_error_network', 'da', 'Netværksfejl. Kontroller venligst din forbindelse.', 'ui'),
  ('erroneous_info_error_network', 'de', 'Netzwerkfehler. Bitte überprüfen Sie Ihre Verbindung.', 'ui'),
  ('erroneous_info_error_network', 'fr', 'Erreur réseau. Veuillez vérifier votre connexion.', 'ui'),
  ('erroneous_info_error_network', 'it', 'Errore di rete. Controllare la connessione.', 'ui'),
  ('erroneous_info_error_network', 'no', 'Nettverksfeil. Vennligst sjekk tilkoblingen din.', 'ui'),
  ('erroneous_info_error_network', 'sv', 'Nätverksfel. Kontrollera din anslutning.', 'ui'),
  ('erroneous_info_error_submission_failed', 'en', 'Failed to submit. Please try again.', 'ui'),
  ('erroneous_info_error_submission_failed', 'da', 'Kunne ikke sende. Prøv venligst igen.', 'ui'),
  ('erroneous_info_error_submission_failed', 'de', 'Fehler beim Senden. Bitte versuchen Sie es erneut.', 'ui'),
  ('erroneous_info_error_submission_failed', 'fr', 'Échec de l''envoi. Veuillez réessayer.', 'ui'),
  ('erroneous_info_error_submission_failed', 'it', 'Invio fallito. Si prega di riprovare.', 'ui'),
  ('erroneous_info_error_submission_failed', 'no', 'Kunne ikke sende. Vennligst prøv igjen.', 'ui'),
  ('erroneous_info_error_submission_failed', 'sv', 'Misslyckades skicka. Försök igen.', 'ui'),
  ('error_retry_button', 'en', 'Retry', 'ui'),
  ('error_retry_button', 'da', 'Prøv igen', 'ui'),
  ('error_retry_button', 'de', 'Wiederholen', 'ui'),
  ('error_retry_button', 'fr', 'Réessayer', 'ui'),
  ('error_retry_button', 'it', 'Riprova', 'ui'),
  ('error_retry_button', 'no', 'Prøv igjen', 'ui'),
  ('error_retry_button', 'sv', 'Försök igen', 'ui'),
  ('feedback_form_checkbox_label', 'en', 'Yes, you can contact me', 'ui'),
  ('feedback_form_checkbox_label', 'da', 'Ja, I kan kontakte mig', 'ui'),
  ('feedback_form_checkbox_label', 'de', 'Ja, Sie können mich kontaktieren', 'ui'),
  ('feedback_form_checkbox_label', 'fr', 'Oui, vous pouvez me contacter', 'ui'),
  ('feedback_form_checkbox_label', 'it', 'Sì, puoi contattarmi', 'ui'),
  ('feedback_form_checkbox_label', 'no', 'Ja, du kan kontakte meg', 'ui'),
  ('feedback_form_checkbox_label', 'sv', 'Ja, du kan kontakta mig', 'ui'),
  ('feedback_form_error_contact_required', 'en', 'Contact info is required (if you want us to contact you)', 'ui'),
  ('feedback_form_error_contact_required', 'da', 'Kontaktoplysninger er påkrævet (hvis du vil kontaktes)', 'ui'),
  ('feedback_form_error_contact_required', 'de', 'Kontaktdaten sind erforderlich (wenn Sie kontaktiert werden möchten)', 'ui'),
  ('feedback_form_error_contact_required', 'fr', 'Les coordonnées sont requises (si vous souhaitez être contacté)', 'ui'),
  ('feedback_form_error_contact_required', 'it', 'Le informazioni di contatto sono obbligatorie (se vuoi essere contattato)', 'ui'),
  ('feedback_form_error_contact_required', 'no', 'Kontaktinformasjon er påkrevd (hvis du vil bli kontaktet)', 'ui'),
  ('feedback_form_error_contact_required', 'sv', 'Kontaktinformation krävs (om du vill bli kontaktad)', 'ui'),
  ('feedback_form_error_name_required', 'en', 'Name is required (if you want us to contact you)', 'ui'),
  ('feedback_form_error_name_required', 'da', 'Navn er påkrævet (hvis du vil kontaktes)', 'ui'),
  ('feedback_form_error_name_required', 'de', 'Name ist erforderlich (wenn Sie kontaktiert werden möchten)', 'ui'),
  ('feedback_form_error_name_required', 'fr', 'Le nom est requis (si vous souhaitez être contacté)', 'ui'),
  ('feedback_form_error_name_required', 'it', 'Il nome è obbligatorio (se vuoi essere contattato)', 'ui'),
  ('feedback_form_error_name_required', 'no', 'Navn er påkrevd (hvis du vil bli kontaktet)', 'ui'),
  ('feedback_form_error_name_required', 'sv', 'Namn krävs (om du vill bli kontaktad)', 'ui'),
  ('feedback_form_hint_contact', 'en', 'email@example.com or +45 12 34 56 78', 'ui'),
  ('feedback_form_hint_contact', 'da', 'email@eksempel.dk eller +45 12 34 56 78', 'ui'),
  ('feedback_form_hint_contact', 'de', 'email@beispiel.de oder +45 12 34 56 78', 'ui'),
  ('feedback_form_hint_contact', 'fr', 'email@exemple.fr ou +45 12 34 56 78', 'ui'),
  ('feedback_form_hint_contact', 'it', 'email@esempio.it o +45 12 34 56 78', 'ui'),
  ('feedback_form_hint_contact', 'no', 'email@eksempel.no eller +45 12 34 56 78', 'ui'),
  ('feedback_form_hint_contact', 'sv', 'email@exempel.se eller +45 12 34 56 78', 'ui'),
  ('feedback_form_subtitle_contact', 'en', 'So we can reach you', 'ui'),
  ('feedback_form_subtitle_contact', 'da', 'Så vi kan kontakte dig', 'ui'),
  ('feedback_form_subtitle_contact', 'de', 'Damit wir Sie erreichen können', 'ui'),
  ('feedback_form_subtitle_contact', 'fr', 'Pour que nous puissions vous joindre', 'ui'),
  ('feedback_form_subtitle_contact', 'it', 'Così possiamo contattarti', 'ui'),
  ('feedback_form_subtitle_contact', 'no', 'Så vi kan nå deg', 'ui'),
  ('feedback_form_subtitle_contact', 'sv', 'Så vi kan nå dig', 'ui'),
  ('feedback_form_title_contact', 'en', 'Email or phone', 'ui'),
  ('feedback_form_title_contact', 'da', 'E-mail eller telefon', 'ui'),
  ('feedback_form_title_contact', 'de', 'E-Mail oder Telefon', 'ui'),
  ('feedback_form_title_contact', 'fr', 'Email ou téléphone', 'ui'),
  ('feedback_form_title_contact', 'it', 'Email o telefono', 'ui'),
  ('feedback_form_title_contact', 'no', 'E-post eller telefon', 'ui'),
  ('feedback_form_title_contact', 'sv', 'E-post eller telefon', 'ui'),
  ('filter_preference_allergen_conflict', 'en', 'This preference conflicts with your allergen exclusions', 'ui'),
  ('filter_preference_allergen_conflict', 'da', 'Denne præference er i konflikt med dine allergen udelukkelser', 'ui'),
  ('filter_preference_allergen_conflict', 'de', 'Diese Präferenz steht im Konflikt mit Ihren Allergenausschlüssen', 'ui'),
  ('filter_preference_allergen_conflict', 'fr', 'Cette préférence est en conflit avec vos exclusions d''allergènes', 'ui'),
  ('filter_preference_allergen_conflict', 'it', 'Questa preferenza è in conflitto con le tue esclusioni di allergeni', 'ui'),
  ('filter_preference_allergen_conflict', 'no', 'Denne preferansen er i konflikt med dine allergenuteslutninger', 'ui'),
  ('filter_preference_allergen_conflict', 'sv', 'Denna preferens är i konflikt med dina allergiuteslutningar', 'ui'),
  ('key_and', 'en', 'and', 'ui'),
  ('key_and', 'da', 'og', 'ui'),
  ('key_and', 'de', 'und', 'ui'),
  ('key_and', 'fr', 'et', 'ui'),
  ('key_and', 'it', 'e', 'ui'),
  ('key_and', 'no', 'og', 'ui'),
  ('key_and', 'sv', 'och', 'ui'),
  ('key_from', 'en', 'From', 'ui'),
  ('key_from', 'da', 'Fra', 'ui'),
  ('key_from', 'de', 'Von', 'ui'),
  ('key_from', 'fr', 'De', 'ui'),
  ('key_from', 'it', 'Da', 'ui'),
  ('key_from', 'no', 'Fra', 'ui'),
  ('key_from', 'sv', 'Från', 'ui'),
  ('key_open', 'en', 'Open', 'ui'),
  ('key_open', 'da', 'Åben', 'ui'),
  ('key_open', 'de', 'Geöffnet', 'ui'),
  ('key_open', 'fr', 'Ouvert', 'ui'),
  ('key_open', 'it', 'Aperto', 'ui'),
  ('key_open', 'no', 'Åpen', 'ui'),
  ('key_open', 'sv', 'Öppet', 'ui'),
  ('key_opening_hours', 'en', 'Opening hours', 'ui'),
  ('key_opening_hours', 'da', 'Åbningstider', 'ui'),
  ('key_opening_hours', 'de', 'Öffnungszeiten', 'ui'),
  ('key_opening_hours', 'fr', 'Horaires d''ouverture', 'ui'),
  ('key_opening_hours', 'it', 'Orari di apertura', 'ui'),
  ('key_opening_hours', 'no', 'Åpningstider', 'ui'),
  ('key_opening_hours', 'sv', 'Öppettider', 'ui'),
  ('key_to', 'en', 'To', 'ui'),
  ('key_to', 'da', 'Til', 'ui'),
  ('key_to', 'de', 'Bis', 'ui'),
  ('key_to', 'fr', 'À', 'ui'),
  ('key_to', 'it', 'A', 'ui'),
  ('key_to', 'no', 'Til', 'ui'),
  ('key_to', 'sv', 'Till', 'ui'),
  ('key_until', 'en', 'Until', 'ui'),
  ('key_until', 'da', 'Indtil', 'ui'),
  ('key_until', 'de', 'Bis', 'ui'),
  ('key_until', 'fr', 'Jusqu''à', 'ui'),
  ('key_until', 'it', 'Fino a', 'ui'),
  ('key_until', 'no', 'Til', 'ui'),
  ('key_until', 'sv', 'Till', 'ui'),
  ('location_permission_denied', 'en', 'Enable location to see distances', 'ui'),
  ('location_permission_denied', 'da', 'Aktiver placering for at se afstand', 'ui'),
  ('location_permission_denied', 'de', 'Standort aktivieren, um Entfernungen zu sehen', 'ui'),
  ('location_permission_denied', 'fr', 'Activez la localisation pour voir les distances', 'ui'),
  ('location_permission_denied', 'it', 'Attiva la posizione per vedere le distanze', 'ui'),
  ('location_permission_denied', 'no', 'Aktiver plassering for å se avstander', 'ui'),
  ('location_permission_denied', 'sv', 'Aktivera plats för att se avstånd', 'ui'),
  ('location_permission_enable', 'en', 'Enable', 'ui'),
  ('location_permission_enable', 'da', 'Aktiver', 'ui'),
  ('location_permission_enable', 'de', 'Aktivieren', 'ui'),
  ('location_permission_enable', 'fr', 'Activer', 'ui'),
  ('location_permission_enable', 'it', 'Attiva', 'ui'),
  ('location_permission_enable', 'no', 'Aktiver', 'ui'),
  ('location_permission_enable', 'sv', 'Aktivera', 'ui'),
  ('menu_contains_allergens', 'en', 'Contains {count} allergen(s)', 'ui'),
  ('menu_contains_allergens', 'da', 'Indeholder {count} allergen(er)', 'ui'),
  ('menu_contains_allergens', 'de', 'Enthält {count} Allergen(e)', 'ui'),
  ('menu_contains_allergens', 'fr', 'Contient {count} allergène(s)', 'ui'),
  ('menu_contains_allergens', 'it', 'Contiene {count} allergene/i', 'ui'),
  ('menu_contains_allergens', 'no', 'Inneholder {count} allergen(er)', 'ui'),
  ('menu_contains_allergens', 'sv', 'Innehåller {count} allergen(er)', 'ui'),
  ('menu_loading', 'en', 'Loading menu...', 'ui'),
  ('menu_loading', 'da', 'Indlæser menu...', 'ui'),
  ('menu_loading', 'de', 'Menü wird geladen...', 'ui'),
  ('menu_loading', 'fr', 'Chargement du menu...', 'ui'),
  ('menu_loading', 'it', 'Caricamento menu...', 'ui'),
  ('menu_loading', 'no', 'Laster meny...', 'ui'),
  ('menu_loading', 'sv', 'Laddar meny...', 'ui'),
  ('search_clear_text', 'en', 'Clear text', 'ui'),
  ('search_clear_text', 'da', 'Ryd tekst', 'ui'),
  ('search_clear_text', 'de', 'Text löschen', 'ui'),
  ('search_clear_text', 'fr', 'Effacer le texte', 'ui'),
  ('search_clear_text', 'it', 'Cancella testo', 'ui'),
  ('search_clear_text', 'no', 'Fjern tekst', 'ui'),
  ('search_clear_text', 'sv', 'Rensa text', 'ui'),
  ('search_error_retry', 'en', 'Try again', 'ui'),
  ('search_error_retry', 'da', 'Prøv igen', 'ui'),
  ('search_error_retry', 'de', 'Erneut versuchen', 'ui'),
  ('search_error_retry', 'fr', 'Réessayer', 'ui'),
  ('search_error_retry', 'it', 'Riprova', 'ui'),
  ('search_error_retry', 'no', 'Prøv igjen', 'ui'),
  ('search_error_retry', 'sv', 'Försök igen', 'ui'),
  ('search_no_results_with_query', 'en', 'No results for ''{query}''', 'ui'),
  ('search_no_results_with_query', 'da', 'Ingen resultater for ''{query}''', 'ui'),
  ('search_no_results_with_query', 'de', 'Keine Ergebnisse für ''{query}''', 'ui'),
  ('search_no_results_with_query', 'fr', 'Aucun résultat pour ''{query}''', 'ui'),
  ('search_no_results_with_query', 'it', 'Nessun risultato per ''{query}''', 'ui'),
  ('search_no_results_with_query', 'no', 'Ingen resultater for ''{query}''', 'ui'),
  ('search_no_results_with_query', 'sv', 'Inga resultat för ''{query}''', 'ui'),
  ('search_placeholder', 'en', 'Search for restaurants...', 'ui'),
  ('search_placeholder', 'da', 'Søg efter restauranter...', 'ui'),
  ('search_placeholder', 'de', 'Nach Restaurants suchen...', 'ui'),
  ('search_placeholder', 'fr', 'Rechercher des restaurants...', 'ui'),
  ('search_placeholder', 'it', 'Cerca ristoranti...', 'ui'),
  ('search_placeholder', 'no', 'Søk etter restauranter...', 'ui'),
  ('search_placeholder', 'sv', 'Sök efter restauranger...', 'ui'),
  ('settings_language_label', 'en', 'Language', 'ui'),
  ('settings_language_label', 'da', 'Sprog', 'ui'),
  ('settings_language_label', 'de', 'Sprache', 'ui'),
  ('settings_language_label', 'fr', 'Langue', 'ui'),
  ('settings_language_label', 'it', 'Lingua', 'ui'),
  ('settings_language_label', 'no', 'Språk', 'ui'),
  ('settings_language_label', 'sv', 'Språk', 'ui'),
  ('settings_select_language_title', 'en', 'Select Language', 'ui'),
  ('settings_select_language_title', 'da', 'Vælg sprog', 'ui'),
  ('settings_select_language_title', 'de', 'Sprache auswählen', 'ui'),
  ('settings_select_language_title', 'fr', 'Sélectionner la langue', 'ui'),
  ('settings_select_language_title', 'it', 'Seleziona lingua', 'ui'),
  ('settings_select_language_title', 'no', 'Velg språk', 'ui'),
  ('settings_select_language_title', 'sv', 'Välj språk', 'ui'),
  ('tab_about', 'en', 'About', 'ui'),
  ('tab_about', 'da', 'Om', 'ui'),
  ('tab_about', 'de', 'Über', 'ui'),
  ('tab_about', 'fr', 'À propos', 'ui'),
  ('tab_about', 'it', 'Informazioni', 'ui'),
  ('tab_about', 'no', 'Om', 'ui'),
  ('tab_about', 'sv', 'Om', 'ui'),
  ('tab_gallery', 'en', 'Gallery', 'ui'),
  ('tab_gallery', 'da', 'Galleri', 'ui'),
  ('tab_gallery', 'de', 'Galerie', 'ui'),
  ('tab_gallery', 'fr', 'Galerie', 'ui'),
  ('tab_gallery', 'it', 'Galleria', 'ui'),
  ('tab_gallery', 'no', 'Galleri', 'ui'),
  ('tab_gallery', 'sv', 'Galleri', 'ui'),
  ('tab_menu', 'en', 'Menu', 'ui'),
  ('tab_menu', 'da', 'Menu', 'ui'),
  ('tab_menu', 'de', 'Menü', 'ui'),
  ('tab_menu', 'fr', 'Menu', 'ui'),
  ('tab_menu', 'it', 'Menu', 'ui'),
  ('tab_menu', 'no', 'Meny', 'ui'),
  ('tab_menu', 'sv', 'Meny', 'ui');

-- ============================================================
-- Upsert Clause (handles duplicates)
-- ============================================================

-- Note: The above INSERT statements use separate statements per section.
-- To enable upsert behavior, modify each INSERT statement to add:
--
-- ON CONFLICT (translation_key, language_code)
-- DO UPDATE SET
--   translation_text = EXCLUDED.translation_text,
--   category = EXCLUDED.category;