-- ============================================================
-- Phase 7 New Keys ONLY (38 keys - descriptive names)
-- These were added during Phase 7 but not yet in Supabase
-- ============================================================
-- CORRECTED: Uses translation_value column (not translation_text)
-- INCLUDES: ON CONFLICT clause for safe upserts
-- ============================================================

INSERT INTO public.ui_translations (translation_key, language_code, translation_value, category)
VALUES
  ('about_description_label', 'en', 'Description', 'ui'),
  ('about_description_label', 'da', 'Beskrivelse', 'ui'),
  ('about_description_label', 'de', 'Beschreibung', 'ui'),
  ('about_description_label', 'fr', 'Description', 'ui'),
  ('about_description_label', 'it', 'Descrizione', 'ui'),
  ('about_description_label', 'no', 'Beskrivelse', 'ui'),
  ('about_description_label', 'sv', 'Beskrivning', 'ui'),
  ('about_payment_options_label', 'en', 'Payment Options', 'ui'),
  ('about_payment_options_label', 'da', 'Betalingsmuligheder', 'ui'),
  ('about_payment_options_label', 'de', 'Zahlungsoptionen', 'ui'),
  ('about_payment_options_label', 'fr', 'Options de paiement', 'ui'),
  ('about_payment_options_label', 'it', 'Opzioni di pagamento', 'ui'),
  ('about_payment_options_label', 'no', 'Betalingsalternativer', 'ui'),
  ('about_payment_options_label', 'sv', 'Betalningsalternativ', 'ui'),
  ('about_report_incorrect_info', 'en', 'Report incorrect information', 'ui'),
  ('about_report_incorrect_info', 'da', 'Rapporter ukorrekte oplysninger', 'ui'),
  ('about_report_incorrect_info', 'de', 'Falsche Informationen melden', 'ui'),
  ('about_report_incorrect_info', 'fr', 'Signaler des informations incorrectes', 'ui'),
  ('about_report_incorrect_info', 'it', 'Segnala informazioni errate', 'ui'),
  ('about_report_incorrect_info', 'no', 'Rapporter feil informasjon', 'ui'),
  ('about_report_incorrect_info', 'sv', 'Rapportera felaktig information', 'ui'),
  ('business_not_found', 'en', 'Business not found', 'ui'),
  ('business_not_found', 'da', 'Virksomhed ikke fundet', 'ui'),
  ('business_not_found', 'de', 'Geschäft nicht gefunden', 'ui'),
  ('business_not_found', 'fr', 'Établissement non trouvé', 'ui'),
  ('business_not_found', 'it', 'Attività non trovata', 'ui'),
  ('business_not_found', 'no', 'Bedrift ikke funnet', 'ui'),
  ('business_not_found', 'sv', 'Företag hittades inte', 'ui'),
  ('currency_chf_cap', 'en', 'Swiss Franc', 'ui'),
  ('currency_chf_cap', 'da', 'Schweiziske franc', 'ui'),
  ('currency_chf_cap', 'de', 'Schweizer Franken', 'ui'),
  ('currency_chf_cap', 'fr', 'Franc suisse', 'ui'),
  ('currency_chf_cap', 'it', 'Franco svizzero', 'ui'),
  ('currency_chf_cap', 'no', 'Sveitsiske franc', 'ui'),
  ('currency_chf_cap', 'sv', 'Schweiziska franc', 'ui'),
  ('currency_cny_cap', 'en', 'Chinese Yuan', 'ui'),
  ('currency_cny_cap', 'da', 'Kinesiske yuan', 'ui'),
  ('currency_cny_cap', 'de', 'Chinesischer Yuan', 'ui'),
  ('currency_cny_cap', 'fr', 'Yuan chinois', 'ui'),
  ('currency_cny_cap', 'it', 'Yuan cinese', 'ui'),
  ('currency_cny_cap', 'no', 'Kinesiske yuan', 'ui'),
  ('currency_cny_cap', 'sv', 'Kinesiska yuan', 'ui'),
  ('currency_jpy_cap', 'en', 'Japanese Yen', 'ui'),
  ('currency_jpy_cap', 'da', 'Japanske yen', 'ui'),
  ('currency_jpy_cap', 'de', 'Japanischer Yen', 'ui'),
  ('currency_jpy_cap', 'fr', 'Yen japonais', 'ui'),
  ('currency_jpy_cap', 'it', 'Yen giapponese', 'ui'),
  ('currency_jpy_cap', 'no', 'Japanske yen', 'ui'),
  ('currency_jpy_cap', 'sv', 'Japanska yen', 'ui'),
  ('currency_pln_cap', 'en', 'Polish Złoty', 'ui'),
  ('currency_pln_cap', 'da', 'Polske złoty', 'ui'),
  ('currency_pln_cap', 'de', 'Polnischer Złoty', 'ui'),
  ('currency_pln_cap', 'fr', 'Złoty polonais', 'ui'),
  ('currency_pln_cap', 'it', 'Złoty polacco', 'ui'),
  ('currency_pln_cap', 'no', 'Polske złoty', 'ui'),
  ('currency_pln_cap', 'sv', 'Polska złoty', 'ui'),
  ('currency_uah_cap', 'en', 'Ukrainian Hryvnia', 'ui'),
  ('currency_uah_cap', 'da', 'Ukrainske hryvnia', 'ui'),
  ('currency_uah_cap', 'de', 'Ukrainische Hrywnja', 'ui'),
  ('currency_uah_cap', 'fr', 'Hryvnia ukrainienne', 'ui'),
  ('currency_uah_cap', 'it', 'Grivna ucraina', 'ui'),
  ('currency_uah_cap', 'no', 'Ukrainske hryvnia', 'ui'),
  ('currency_uah_cap', 'sv', 'Ukrainska hryvnia', 'ui'),
  ('erroneous_info_error_network', 'en', 'Network error. Please check your connection.', 'ui'),
  ('erroneous_info_error_network', 'da', 'Netværksfejl. Kontroller venligst din forbindelse.', 'ui'),
  ('erroneous_info_error_network', 'de', 'Netzwerkfehler. Bitte überprüfen Sie Ihre Verbindung.', 'ui'),
  ('erroneous_info_error_network', 'fr', 'Erreur réseau. Veuillez vérifier votre connexion.', 'ui'),
  ('erroneous_info_error_network', 'it', 'Errore di rete. Controllare la connessione.', 'ui'),
  ('erroneous_info_error_network', 'no', 'Nettverksfeil. Vennligst sjekk tilkoblingen din.', 'ui'),
  ('erroneous_info_error_network', 'sv', 'Nätverksfel. Kontrollera din anslutning.', 'ui'),
  ('erroneous_info_error_submission_failed', 'en', 'Failed to submit. Please try again.', 'ui'),
  ('erroneous_info_error_submission_failed', 'da', 'Kunne ikke sende. Prøv venligst igen.', 'ui'),
  ('erroneous_info_error_submission_failed', 'de', 'Fehler beim Senden. Bitte versuchen Sie es erneut.', 'ui'),
  ('erroneous_info_error_submission_failed', 'fr', 'Échec de l''envoi. Veuillez réessayer.', 'ui'),
  ('erroneous_info_error_submission_failed', 'it', 'Invio fallito. Si prega di riprovare.', 'ui'),
  ('erroneous_info_error_submission_failed', 'no', 'Kunne ikke sende. Vennligst prøv igjen.', 'ui'),
  ('erroneous_info_error_submission_failed', 'sv', 'Misslyckades skicka. Försök igen.', 'ui'),
  ('error_retry_button', 'en', 'Retry', 'ui'),
  ('error_retry_button', 'da', 'Prøv igen', 'ui'),
  ('error_retry_button', 'de', 'Wiederholen', 'ui'),
  ('error_retry_button', 'fr', 'Réessayer', 'ui'),
  ('error_retry_button', 'it', 'Riprova', 'ui'),
  ('error_retry_button', 'no', 'Prøv igjen', 'ui'),
  ('error_retry_button', 'sv', 'Försök igen', 'ui'),
  ('feedback_form_checkbox_label', 'en', 'Yes, you can contact me', 'ui'),
  ('feedback_form_checkbox_label', 'da', 'Ja, I kan kontakte mig', 'ui'),
  ('feedback_form_checkbox_label', 'de', 'Ja, Sie können mich kontaktieren', 'ui'),
  ('feedback_form_checkbox_label', 'fr', 'Oui, vous pouvez me contacter', 'ui'),
  ('feedback_form_checkbox_label', 'it', 'Sì, puoi contattarmi', 'ui'),
  ('feedback_form_checkbox_label', 'no', 'Ja, du kan kontakte meg', 'ui'),
  ('feedback_form_checkbox_label', 'sv', 'Ja, du kan kontakta mig', 'ui'),
  ('feedback_form_error_contact_required', 'en', 'Contact info is required (if you want us to contact you)', 'ui'),
  ('feedback_form_error_contact_required', 'da', 'Kontaktoplysninger er påkrævet (hvis du vil kontaktes)', 'ui'),
  ('feedback_form_error_contact_required', 'de', 'Kontaktdaten sind erforderlich (wenn Sie kontaktiert werden möchten)', 'ui'),
  ('feedback_form_error_contact_required', 'fr', 'Les coordonnées sont requises (si vous souhaitez être contacté)', 'ui'),
  ('feedback_form_error_contact_required', 'it', 'Le informazioni di contatto sono obbligatorie (se vuoi essere contattato)', 'ui'),
  ('feedback_form_error_contact_required', 'no', 'Kontaktinformasjon er påkrevd (hvis du vil bli kontaktet)', 'ui'),
  ('feedback_form_error_contact_required', 'sv', 'Kontaktinformation krävs (om du vill bli kontaktad)', 'ui'),
  ('feedback_form_error_name_required', 'en', 'Name is required (if you want us to contact you)', 'ui'),
  ('feedback_form_error_name_required', 'da', 'Navn er påkrævet (hvis du vil kontaktes)', 'ui'),
  ('feedback_form_error_name_required', 'de', 'Name ist erforderlich (wenn Sie kontaktiert werden möchten)', 'ui'),
  ('feedback_form_error_name_required', 'fr', 'Le nom est requis (si vous souhaitez être contacté)', 'ui'),
  ('feedback_form_error_name_required', 'it', 'Il nome è obbligatorio (se vuoi essere contattato)', 'ui'),
  ('feedback_form_error_name_required', 'no', 'Navn er påkrevd (hvis du vil bli kontaktet)', 'ui'),
  ('feedback_form_error_name_required', 'sv', 'Namn krävs (om du vill bli kontaktad)', 'ui'),
  ('feedback_form_hint_contact', 'en', 'email@example.com or +45 12 34 56 78', 'ui'),
  ('feedback_form_hint_contact', 'da', 'email@eksempel.dk eller +45 12 34 56 78', 'ui'),
  ('feedback_form_hint_contact', 'de', 'email@beispiel.de oder +45 12 34 56 78', 'ui'),
  ('feedback_form_hint_contact', 'fr', 'email@exemple.fr ou +45 12 34 56 78', 'ui'),
  ('feedback_form_hint_contact', 'it', 'email@esempio.it o +45 12 34 56 78', 'ui'),
  ('feedback_form_hint_contact', 'no', 'email@eksempel.no eller +45 12 34 56 78', 'ui'),
  ('feedback_form_hint_contact', 'sv', 'email@exempel.se eller +45 12 34 56 78', 'ui'),
  ('feedback_form_subtitle_contact', 'en', 'So we can reach you', 'ui'),
  ('feedback_form_subtitle_contact', 'da', 'Så vi kan kontakte dig', 'ui'),
  ('feedback_form_subtitle_contact', 'de', 'Damit wir Sie erreichen können', 'ui'),
  ('feedback_form_subtitle_contact', 'fr', 'Pour que nous puissions vous joindre', 'ui'),
  ('feedback_form_subtitle_contact', 'it', 'Così possiamo contattarti', 'ui'),
  ('feedback_form_subtitle_contact', 'no', 'Så vi kan nå deg', 'ui'),
  ('feedback_form_subtitle_contact', 'sv', 'Så vi kan nå dig', 'ui'),
  ('feedback_form_title_contact', 'en', 'Email or phone', 'ui'),
  ('feedback_form_title_contact', 'da', 'E-mail eller telefon', 'ui'),
  ('feedback_form_title_contact', 'de', 'E-Mail oder Telefon', 'ui'),
  ('feedback_form_title_contact', 'fr', 'Email ou téléphone', 'ui'),
  ('feedback_form_title_contact', 'it', 'Email o telefono', 'ui'),
  ('feedback_form_title_contact', 'no', 'E-post eller telefon', 'ui'),
  ('feedback_form_title_contact', 'sv', 'E-post eller telefon', 'ui'),
  ('filter_preference_allergen_conflict', 'en', 'This preference conflicts with your allergen exclusions', 'ui'),
  ('filter_preference_allergen_conflict', 'da', 'Denne præference er i konflikt med dine allergen udelukkelser', 'ui'),
  ('filter_preference_allergen_conflict', 'de', 'Diese Präferenz steht im Konflikt mit Ihren Allergenausschlüssen', 'ui'),
  ('filter_preference_allergen_conflict', 'fr', 'Cette préférence est en conflit avec vos exclusions d''allergènes', 'ui'),
  ('filter_preference_allergen_conflict', 'it', 'Questa preferenza è in conflitto con le tue esclusioni di allergeni', 'ui'),
  ('filter_preference_allergen_conflict', 'no', 'Denne preferansen er i konflikt med dine allergenuteslutninger', 'ui'),
  ('filter_preference_allergen_conflict', 'sv', 'Denna preferens är i konflikt med dina allergiuteslutningar', 'ui'),
  ('key_and', 'en', 'and', 'ui'),
  ('key_and', 'da', 'og', 'ui'),
  ('key_and', 'de', 'und', 'ui'),
  ('key_and', 'fr', 'et', 'ui'),
  ('key_and', 'it', 'e', 'ui'),
  ('key_and', 'no', 'og', 'ui'),
  ('key_and', 'sv', 'och', 'ui'),
  ('key_from', 'en', 'From', 'ui'),
  ('key_from', 'da', 'Fra', 'ui'),
  ('key_from', 'de', 'Von', 'ui'),
  ('key_from', 'fr', 'De', 'ui'),
  ('key_from', 'it', 'Da', 'ui'),
  ('key_from', 'no', 'Fra', 'ui'),
  ('key_from', 'sv', 'Från', 'ui'),
  ('key_open', 'en', 'Open', 'ui'),
  ('key_open', 'da', 'Åben', 'ui'),
  ('key_open', 'de', 'Geöffnet', 'ui'),
  ('key_open', 'fr', 'Ouvert', 'ui'),
  ('key_open', 'it', 'Aperto', 'ui'),
  ('key_open', 'no', 'Åpen', 'ui'),
  ('key_open', 'sv', 'Öppet', 'ui'),
  ('key_opening_hours', 'en', 'Opening hours', 'ui'),
  ('key_opening_hours', 'da', 'Åbningstider', 'ui'),
  ('key_opening_hours', 'de', 'Öffnungszeiten', 'ui'),
  ('key_opening_hours', 'fr', 'Horaires d''ouverture', 'ui'),
  ('key_opening_hours', 'it', 'Orari di apertura', 'ui'),
  ('key_opening_hours', 'no', 'Åpningstider', 'ui'),
  ('key_opening_hours', 'sv', 'Öppettider', 'ui'),
  ('key_to', 'en', 'To', 'ui'),
  ('key_to', 'da', 'Til', 'ui'),
  ('key_to', 'de', 'Bis', 'ui'),
  ('key_to', 'fr', 'À', 'ui'),
  ('key_to', 'it', 'A', 'ui'),
  ('key_to', 'no', 'Til', 'ui'),
  ('key_to', 'sv', 'Till', 'ui'),
  ('key_until', 'en', 'Until', 'ui'),
  ('key_until', 'da', 'Indtil', 'ui'),
  ('key_until', 'de', 'Bis', 'ui'),
  ('key_until', 'fr', 'Jusqu''à', 'ui'),
  ('key_until', 'it', 'Fino a', 'ui'),
  ('key_until', 'no', 'Til', 'ui'),
  ('key_until', 'sv', 'Till', 'ui'),
  ('location_permission_denied', 'en', 'Enable location to see distances', 'ui'),
  ('location_permission_denied', 'da', 'Aktiver placering for at se afstand', 'ui'),
  ('location_permission_denied', 'de', 'Standort aktivieren, um Entfernungen zu sehen', 'ui'),
  ('location_permission_denied', 'fr', 'Activez la localisation pour voir les distances', 'ui'),
  ('location_permission_denied', 'it', 'Attiva la posizione per vedere le distanze', 'ui'),
  ('location_permission_denied', 'no', 'Aktiver plassering for å se avstander', 'ui'),
  ('location_permission_denied', 'sv', 'Aktivera plats för att se avstånd', 'ui'),
  ('location_permission_enable', 'en', 'Enable', 'ui'),
  ('location_permission_enable', 'da', 'Aktiver', 'ui'),
  ('location_permission_enable', 'de', 'Aktivieren', 'ui'),
  ('location_permission_enable', 'fr', 'Activer', 'ui'),
  ('location_permission_enable', 'it', 'Attiva', 'ui'),
  ('location_permission_enable', 'no', 'Aktiver', 'ui'),
  ('location_permission_enable', 'sv', 'Aktivera', 'ui'),
  ('menu_contains_allergens', 'en', 'Contains {count} allergen(s)', 'ui'),
  ('menu_contains_allergens', 'da', 'Indeholder {count} allergen(er)', 'ui'),
  ('menu_contains_allergens', 'de', 'Enthält {count} Allergen(e)', 'ui'),
  ('menu_contains_allergens', 'fr', 'Contient {count} allergène(s)', 'ui'),
  ('menu_contains_allergens', 'it', 'Contiene {count} allergene/i', 'ui'),
  ('menu_contains_allergens', 'no', 'Inneholder {count} allergen(er)', 'ui'),
  ('menu_contains_allergens', 'sv', 'Innehåller {count} allergen(er)', 'ui'),
  ('menu_loading', 'en', 'Loading menu...', 'ui'),
  ('menu_loading', 'da', 'Indlæser menu...', 'ui'),
  ('menu_loading', 'de', 'Menü wird geladen...', 'ui'),
  ('menu_loading', 'fr', 'Chargement du menu...', 'ui'),
  ('menu_loading', 'it', 'Caricamento menu...', 'ui'),
  ('menu_loading', 'no', 'Laster meny...', 'ui'),
  ('menu_loading', 'sv', 'Laddar meny...', 'ui'),
  ('search_clear_text', 'en', 'Clear text', 'ui'),
  ('search_clear_text', 'da', 'Ryd tekst', 'ui'),
  ('search_clear_text', 'de', 'Text löschen', 'ui'),
  ('search_clear_text', 'fr', 'Effacer le texte', 'ui'),
  ('search_clear_text', 'it', 'Cancella testo', 'ui'),
  ('search_clear_text', 'no', 'Fjern tekst', 'ui'),
  ('search_clear_text', 'sv', 'Rensa text', 'ui'),
  ('search_error_retry', 'en', 'Try again', 'ui'),
  ('search_error_retry', 'da', 'Prøv igen', 'ui'),
  ('search_error_retry', 'de', 'Erneut versuchen', 'ui'),
  ('search_error_retry', 'fr', 'Réessayer', 'ui'),
  ('search_error_retry', 'it', 'Riprova', 'ui'),
  ('search_error_retry', 'no', 'Prøv igjen', 'ui'),
  ('search_error_retry', 'sv', 'Försök igen', 'ui'),
  ('search_no_results_with_query', 'en', 'No results for ''{query}''', 'ui'),
  ('search_no_results_with_query', 'da', 'Ingen resultater for ''{query}''', 'ui'),
  ('search_no_results_with_query', 'de', 'Keine Ergebnisse für ''{query}''', 'ui'),
  ('search_no_results_with_query', 'fr', 'Aucun résultat pour ''{query}''', 'ui'),
  ('search_no_results_with_query', 'it', 'Nessun risultato per ''{query}''', 'ui'),
  ('search_no_results_with_query', 'no', 'Ingen resultater for ''{query}''', 'ui'),
  ('search_no_results_with_query', 'sv', 'Inga resultat för ''{query}''', 'ui'),
  ('search_placeholder', 'en', 'Search for restaurants...', 'ui'),
  ('search_placeholder', 'da', 'Søg efter restauranter...', 'ui'),
  ('search_placeholder', 'de', 'Nach Restaurants suchen...', 'ui'),
  ('search_placeholder', 'fr', 'Rechercher des restaurants...', 'ui'),
  ('search_placeholder', 'it', 'Cerca ristoranti...', 'ui'),
  ('search_placeholder', 'no', 'Søk etter restauranter...', 'ui'),
  ('search_placeholder', 'sv', 'Sök efter restauranger...', 'ui'),
  ('settings_language_label', 'en', 'Language', 'ui'),
  ('settings_language_label', 'da', 'Sprog', 'ui'),
  ('settings_language_label', 'de', 'Sprache', 'ui'),
  ('settings_language_label', 'fr', 'Langue', 'ui'),
  ('settings_language_label', 'it', 'Lingua', 'ui'),
  ('settings_language_label', 'no', 'Språk', 'ui'),
  ('settings_language_label', 'sv', 'Språk', 'ui'),
  ('settings_select_language_title', 'en', 'Select Language', 'ui'),
  ('settings_select_language_title', 'da', 'Vælg sprog', 'ui'),
  ('settings_select_language_title', 'de', 'Sprache auswählen', 'ui'),
  ('settings_select_language_title', 'fr', 'Sélectionner la langue', 'ui'),
  ('settings_select_language_title', 'it', 'Seleziona lingua', 'ui'),
  ('settings_select_language_title', 'no', 'Velg språk', 'ui'),
  ('settings_select_language_title', 'sv', 'Välj språk', 'ui'),
  ('tab_about', 'en', 'About', 'ui'),
  ('tab_about', 'da', 'Om', 'ui'),
  ('tab_about', 'de', 'Über', 'ui'),
  ('tab_about', 'fr', 'À propos', 'ui'),
  ('tab_about', 'it', 'Informazioni', 'ui'),
  ('tab_about', 'no', 'Om', 'ui'),
  ('tab_about', 'sv', 'Om', 'ui'),
  ('tab_gallery', 'en', 'Gallery', 'ui'),
  ('tab_gallery', 'da', 'Galleri', 'ui'),
  ('tab_gallery', 'de', 'Galerie', 'ui'),
  ('tab_gallery', 'fr', 'Galerie', 'ui'),
  ('tab_gallery', 'it', 'Galleria', 'ui'),
  ('tab_gallery', 'no', 'Galleri', 'ui'),
  ('tab_gallery', 'sv', 'Galleri', 'ui'),
  ('tab_menu', 'en', 'Menu', 'ui'),
  ('tab_menu', 'da', 'Menu', 'ui'),
  ('tab_menu', 'de', 'Menü', 'ui'),
  ('tab_menu', 'fr', 'Menu', 'ui'),
  ('tab_menu', 'it', 'Menu', 'ui'),
  ('tab_menu', 'no', 'Meny', 'ui'),
  ('tab_menu', 'sv', 'Meny', 'ui')
ON CONFLICT (language_code, translation_key)
DO UPDATE SET
  translation_value = EXCLUDED.translation_value,
  category = EXCLUDED.category;
